import knex from 'knex';
import knexConfig from '../knexfile.manajemen.js';

const environment = process.env.NODE_ENV || 'development';
const db = knex(knexConfig[environment]);

const mappingData = [
  { name: "Tim Pengembang Sekolah (TPS)", category: "Pengembangan Program" },
  { name: "Workshop Pengembangan Sekolah", category: "Forum/Rapat" },
  { name: "Analisis Konteks", category: "Pengembangan Program" },
  { name: "Analisis Kompetitor", category: "Pengembangan Program" },
  { name: "EVADIR (Evaluasi Diri Sekolah)", category: "Pengembangan Program" },
  { name: "Analisis SWOT", category: "Pengembangan Program" },
  { name: "Survei Kepuasan", category: "Pengembangan Program" },
  { name: "Rapor Pendidikan", category: "Penyusunan Dokumen" },
  { name: "Trace Study Lulusan", category: "Pengembangan Program" },
  { name: "Blue Print Sekolah", category: "Penyusunan Dokumen" },
  { name: "RIPS (Rencana Induk Pengembangan Sekolah)", category: "Penyusunan Dokumen" },
  { name: "Visi, Misi & Tujuan", category: "Penyusunan Dokumen" },
  { name: "Indikator Mutu Program, Strategi Perencanaan dan Pelaksanaan Program", category: "Penyusunan Dokumen" },
  { name: "RKJM (Rencana Kerja Jangka Menengah)", category: "Penyusunan Dokumen" },
  { name: "RKT (Rencana Kerja Tahunan)", category: "Penyusunan Dokumen" },
  { name: "Program Kerja Sekolah", category: "Penyusunan Dokumen" },
  { name: "Program Kerja Kepala Sekolah", category: "Penyusunan Dokumen" },
  { name: "Program Kerja Bidang Kurikulum", category: "Penyusunan Dokumen" },
  { name: "Program Kerja Bidang Kesiswaan", category: "Penyusunan Dokumen" },
  { name: "Program Kerja Bidang Tata Usaha", category: "Penyusunan Dokumen" },
  { name: "Program Kerja Bidang SDM", category: "Penyusunan Dokumen" },
  { name: "Program Kerja Bidang Sarpras", category: "Penyusunan Dokumen" },
  { name: "Program Kerja Bidang Keuangan", category: "Penyusunan Dokumen" },
  { name: "Program Kerja Bidang Pemasaran", category: "Penyusunan Dokumen" },
  { name: "Program Kerja Bidang Humas", category: "Penyusunan Dokumen" },
  { name: "Program Kerja Guru Kelas", category: "Penyusunan Dokumen" },
  { name: "Program Kerja Guru Mapel", category: "Penyusunan Dokumen" },
  { name: "Program Kerja Bidang Kebersihan", category: "Penyusunan Dokumen" },
  { name: "Proker Dapur", category: "Pengembangan Program" },
  { name: "Proker BOS", category: "Pengembangan Program" },
  { name: "Proker Operator", category: "Pengembangan Program" },
  { name: "Kalender Kerja & Schedule Time", category: "Penyusunan Dokumen" },
  { name: "SKL", category: "Penyusunan Dokumen" },
  { name: "KKM", category: "Penyusunan Dokumen" },
  { name: "Kriteria Kenaikan & Kelulusan", category: "Kegiatan Siswa" },
  { name: "Tim Pengembang Kurikulum (TPK)", category: "Pengembangan Program" },
  { name: "Workshop Pengembangan Kurikulum", category: "Forum/Rapat" },
  { name: "Dokumen I Kurikulum: KSP", category: "Penyusunan Dokumen" },
  { name: "Dokumen II Kurikulum: Silabus/ATP", category: "Penyusunan Dokumen" },
  { name: "Dokumen III Kurikulum: RPP/Modul Ajar", category: "Penyusunan Dokumen" },
  { name: "Struktur Kurikulum", category: "Penyusunan Dokumen" },
  { name: "Capaian Pembelajaran (CP)", category: "Penyusunan Dokumen" },
  { name: "Kalender Pendidikan & Agenda Kegiatan", category: "Pengembangan Program" },
  { name: "Agenda Kegiatan", category: "Pengembangan Program" },
  { name: "Buku Pelajaran", category: "Pengembangan Program" },
  { name: "Program Akademik", category: "Penyusunan Dokumen" },
  { name: "Pedoman Akademik", category: "Penyusunan Dokumen" },
  { name: "Program Takhoshush", category: "Pengembangan Program" },
  { name: "Sosialisasi Program Kurikulum", category: "Sosialisasi" },
  { name: "Pedoman Pengajaran", category: "Penyusunan Dokumen" },
  { name: "Jadwal Pelajaran", category: "Pengembangan Program" },
  { name: "Analisis Waktu Efektif", category: "Pengembangan Program" },
  { name: "Prota & Prosem", category: "Penyusunan Dokumen" },
  { name: "Analisis Kebutuhan Bahan dan Alat Pembelajaran", category: "Pengembangan Program" },
  { name: "Buku Kerja Guru (BKG)", category: "Penyusunan Dokumen" },
  { name: "Administrasi Proses Pembelajaran", category: "Penyusunan Dokumen" },
  { name: "Kehadiran Murid", category: "Pengembangan Program" },
  { name: "Pelaksanaan Pembelajaran", category: "Pengembangan Program" },
  { name: "Monitoring Evaluasi Pembelajaran", category: "Pengembangan Program" },
  { name: "Pengayaan Kognitif Calon Lulusan", category: "Pengembangan Program" },
  { name: "Drill TKA", category: "Pengembangan Program" },
  { name: "Pembelajaran Ramadhan", category: "Kegiatan Siswa" },
  { name: "Kombel", category: "Pengembangan Program" },
  { name: "Refleksi Belajar", category: "Pengembangan Program" },
  { name: "Pembelajaran Proyek", category: "Pengembangan Program" },
  { name: "Martikulasi Literasi", category: "Kegiatan Siswa" },
  { name: "Martikulasi Numerasi", category: "Kegiatan Siswa" },
  { name: "Gamifikasi", category: "Kegiatan Siswa" },
  { name: "Challange Board", category: "Kegiatan Siswa" },
  { name: "Seminar Ilmiah", category: "Kegiatan Siswa" },
  { name: "Tim Pengajar Al-Qur'an", category: "Pengembangan Program" },
  { name: "SKL & Target Al-Qur'an", category: "Penyusunan Dokumen" },
  { name: "Struktur Kurikulum Al-Qur'an", category: "Penyusunan Dokumen" },
  { name: "CP Pembelajaran Al-Qur'an", category: "Penyusunan Dokumen" },
  { name: "Analisis Waktu Efektif Pembelajaran Al-Qur'an", category: "Pengembangan Program" },
  { name: "Silabus Pembelajaran Al-Qur'an", category: "Penyusunan Dokumen" },
  { name: "Juknis Pembelajaran Al-Qur'an", category: "Penyusunan Dokumen" },
  { name: "Buku Pembelajaran Al-Qur'an", category: "Pengembangan Program" },
  { name: "Administrasi Pembelajaran Al-Qur'an", category: "Penyusunan Dokumen" },
  { name: "Timeline Pembelajaran Al-Qur'an", category: "Penyusunan Dokumen" },
  { name: "Program Kerja Pembelajaran Al-Qur'an", category: "Penyusunan Dokumen" },
  { name: "Sosialisasi Program Al-Qur'an", category: "Sosialisasi" },
  { name: "Pelacement Test", category: "Pengembangan Program" },
  { name: "Halaqah", category: "Kegiatan Siswa" },
  { name: "KBM Al-Qur'an", category: "Kegiatan Siswa" },
  { name: "Evaluasi KBM Al-Qur'an", category: "Kegiatan Siswa" },
  { name: "Gamifikasi Pembelajaran Al-Qur'an", category: "Kegiatan Siswa" },
  { name: "Konseling & Refleksi Program Al-Qur'an", category: "Pengembangan Program" },
  { name: "Quranic Camp", category: "Kegiatan Siswa" },
  { name: "Sanad Tuhfatul Athfal", category: "Pengembangan Program" },
  { name: "Sanad Al-Fatihah", category: "Pengembangan Program" },
  { name: "Sertifikasi Tahfizh Kemenag", category: "Pengembangan Program" },
  { name: "Pembiasaan Tilawah", category: "Pengembangan Program" },
  { name: "Takhoshush Al-Qur’an Liburan", category: "Kegiatan Siswa" },
  { name: "Tasmi' Akhir Al-Qur'an", category: "Kegiatan Siswa" },
  { name: "Ujian Akhir Al-Qur'an", category: "Kegiatan Siswa" },
  { name: "Tim Pengajar Bahasa", category: "Pengembangan Program" },
  { name: "SKL & Target Bahasa", category: "Penyusunan Dokumen" },
  { name: "Struktur Kurikulum Bahasa", category: "Penyusunan Dokumen" },
  { name: "CP Pembelajaran Bahasa", category: "Penyusunan Dokumen" },
  { name: "Analisis Waktu Efektif Pembelajaran Bahasa", category: "Pengembangan Program" },
  { name: "Silabus Pembelajaran Bahasa", category: "Penyusunan Dokumen" },
  { name: "Juknis Pembelajaran Bahasa", category: "Penyusunan Dokumen" },
  { name: "Buku Pembelajaran Bahasa", category: "Pengembangan Program" },
  { name: "Administrasi Pembelajaran Bahasa", category: "Penyusunan Dokumen" },
  { name: "Timeline Pembelajaran Bahasa", category: "Penyusunan Dokumen" },
  { name: "Program Kerja Pembelajaran Bahasa", category: "Penyusunan Dokumen" },
  { name: "Sosialisasi Program Bahasa", category: "Sosialisasi" },
  { name: "KBM Bahasa", category: "Kegiatan Siswa" },
  { name: "Mufradat", category: "Kegiatan Siswa" },
  { name: "Muhadatsah", category: "Kegiatan Siswa" },
  { name: "Evaluasi Program Bahasa", category: "Pengembangan Program" },
  { name: "Gamifikasi Bahasa", category: "Kegiatan Siswa" },
  { name: "Konseling Bahasa", category: "Pengembangan Program" },
  { name: "Language Camp", category: "Kegiatan Siswa" },
  { name: "Lingkungan Bahasa (Sosial)", category: "Pengembangan Program" },
  { name: "Lingkungan Bahasa (Fisik)", category: "Pengembangan Program" },
  { name: "Kelas Karantina Bahasa", category: "Kegiatan Siswa" },
  { name: "Kelas Martikulasi Bahasa", category: "Kegiatan Siswa" },
  { name: "Laboratorium Bahasa", category: "Pengembangan Program" },
  { name: "Proyek Bahasa", category: "Kegiatan Siswa" },
  { name: "Trip Bahasa", category: "Kegiatan Siswa" },
  { name: "Tim Pengajar Kewirausahaan", category: "Pengembangan Program" },
  { name: "SKL & Target Kewirausahaan", category: "Penyusunan Dokumen" },
  { name: "Struktur Kurikulum Kewirausahaan", category: "Penyusunan Dokumen" },
  { name: "CP Pembelajaran Kewirausahaan", category: "Penyusunan Dokumen" },
  { name: "Analisis Waktu Efektif Pembelajaran Kewirausahaan", category: "Pengembangan Program" },
  { name: "Silabus Pembelajaran Kewirausahaan", category: "Penyusunan Dokumen" },
  { name: "Juknis Pembelajaran Kewirausahaan", category: "Penyusunan Dokumen" },
  { name: "Buku Pembelajaran Kewirausahaan", category: "Pengembangan Program" },
  { name: "Administrasi Pembelajaran Kewirausahaan", category: "Penyusunan Dokumen" },
  { name: "Timeline Pembelajaran Kewirausahaan", category: "Penyusunan Dokumen" },
  { name: "Program Kerja Pembelajaran Kewirausahaan", category: "Penyusunan Dokumen" },
  { name: "Sosialisasi Program Kewirausahaan", category: "Sosialisasi" },
  { name: "Kelas Kewirausahaan", category: "Kegiatan Siswa" },
  { name: "Gamifikasi Kewirausahaan", category: "Kegiatan Siswa" },
  { name: "Konseling Kewirausahaan", category: "Pengembangan Program" },
  { name: "Proyek Kewirausahaan", category: "Kegiatan Siswa" },
  { name: "Trip Kewirausahaan", category: "Kegiatan Siswa" },
  { name: "Tim Pengajar IT", category: "Pengembangan Program" },
  { name: "SKL & Target IT", category: "Penyusunan Dokumen" },
  { name: "Struktur Kurikulum IT", category: "Penyusunan Dokumen" },
  { name: "CP Pembelajaran IT", category: "Penyusunan Dokumen" },
  { name: "Analisis Waktu Efektif Pembelajaran IT", category: "Pengembangan Program" },
  { name: "Silabus Pembelajaran IT", category: "Penyusunan Dokumen" },
  { name: "Juknis Pembelajaran IT", category: "Penyusunan Dokumen" },
  { name: "Buku Pembelajaran IT", category: "Pengembangan Program" },
  { name: "Administrasi Pembelajaran IT", category: "Penyusunan Dokumen" },
  { name: "Timeline Pembelajaran IT", category: "Penyusunan Dokumen" },
  { name: "Program Kerja Pembelajaran IT", category: "Penyusunan Dokumen" },
  { name: "Sosialisasi Program IT", category: "Sosialisasi" },
  { name: "Kelas IT", category: "Kegiatan Siswa" },
  { name: "Gamifikasi IT", category: "Kegiatan Siswa" },
  { name: "Konseling IT", category: "Pengembangan Program" },
  { name: "Proyek IT", category: "Kegiatan Siswa" },
  { name: "Bimbingan & Konseling (BK)", category: "Pengembangan Program" },
  { name: "Tes Psikologi", category: "Pengembangan Program" },
  { name: "Penyuluhan Anti Bullying", category: "Sosialisasi" },
  { name: "Screening Indikasi Anti Bullying", category: "Pengembangan Program" },
  { name: "Kelompok Bimbingan", category: "Pengembangan Program" },
  { name: "Satgas Anti Bullying", category: "Pengembangan Program" },
  { name: "Sistem Pengaduan, Penanganan dan Pencegahan Bullying", category: "Pengembangan Program" },
  { name: "Kajian Parenting", category: "Pengembangan Program" },
  { name: "Tata Tertib Siswa", category: "Pengembangan Program" },
  { name: "Pembiasaan Karakter", category: "Pengembangan Program" },
  { name: "Spiritual Morning", category: "Kegiatan Siswa" },
  { name: "Shalat Dhuha", category: "Kegiatan Siswa" },
  { name: "Upacara Hari Senin", category: "Kegiatan Siswa" },
  { name: "Class Meeting Semester 1", category: "Kegiatan Siswa" },
  { name: "Class Meeting Semester 2", category: "Kegiatan Siswa" },
  { name: "Penyambutan Kedatangan Santri Lama", category: "Kegiatan Siswa" },
  { name: "Penyambutan Kedatangan Santri Baru", category: "Kegiatan Siswa" },
  { name: "MATAN (Masa Ta'aruf Santri)", category: "Kegiatan Siswa" },
  { name: "Kegiatan Awal Tahun", category: "Pengembangan Program" },
  { name: "Market Day", category: "Kegiatan Siswa" },
  { name: "Perpisahan", category: "Kegiatan Siswa" },
  { name: "Kelulusan", category: "Kegiatan Siswa" },
  { name: "Pengayaan Nonkognitif Calon Lulusan", category: "Pengembangan Program" },
  { name: "LDKS (Latihan Dasar Kepemimpinan Siswa)", category: "Kegiatan Siswa" },
  { name: "Aktivitas Sabtu Ramadhan", category: "Kegiatan Siswa" },
  { name: "Self Developement", category: "Pengembangan Program" },
  { name: "Tata Tertib Asrama", category: "Pengembangan Program" },
  { name: "Kemusyrifan", category: "Pengembangan Program" },
  { name: "Perizinan", category: "Pengembangan Program" },
  { name: "Pembiasaan Ibadah", category: "Pengembangan Program" },
  { name: "Muhasabah", category: "Kegiatan Siswa" },
  { name: "Infaq Jum'at", category: "Kegiatan Siswa" },
  { name: "Muhadharah Pekanan", category: "Kegiatan Siswa" },
  { name: "Muhadharah Bulanan", category: "Kegiatan Siswa" },
  { name: "Da'wah Journey", category: "Kegiatan Siswa" },
  { name: "Penjengukan", category: "Kegiatan Siswa" },
  { name: "Perpulangan", category: "Kegiatan Siswa" },
  { name: "Penelponan", category: "Kegiatan Siswa" },
  { name: "Program Ramadhan", category: "Kegiatan Siswa" },
  { name: "Tarhib Ramadhan", category: "Kegiatan Siswa" },
  { name: "I'tikaf Ramadhan", category: "Kegiatan Siswa" },
  { name: "Shalat Tarawih", category: "Kegiatan Siswa" },
  { name: "1 Muharram", category: "Kegiatan Siswa" },
  { name: "Isra' Mi'raj", category: "Kegiatan Siswa" },
  { name: "Maulid Nabi", category: "Kegiatan Siswa" },
  { name: "Pemetaan Minat & Bakat", category: "Kegiatan Siswa" },
  { name: "Papan Kompetisi", category: "Kegiatan Siswa" },
  { name: "Latihan Olimpiade", category: "Kegiatan Siswa" },
  { name: "Self Learning Olimpiade", category: "Kegiatan Siswa" },
  { name: "Lomba: PAI Fair", category: "Kegiatan Siswa" },
  { name: "Pembinaan Olimpiade", category: "Kegiatan Siswa" },
  { name: "Uji Soal MNR", category: "Kegiatan Siswa" },
  { name: "Program Pendidikan Karakter", category: "Kegiatan Siswa" },
  { name: "Lingkungan Kelas Berkarakter", category: "Kegiatan Siswa" },
  { name: "Lingkungan Sekolah Berkarakter", category: "Kegiatan Siswa" },
  { name: "Program Liburan Tengah Semester 1", category: "Kegiatan Siswa" },
  { name: "Program Liburan Akhir Semester 1", category: "Kegiatan Siswa" },
  { name: "Program Liburan Tengah Semester 2", category: "Kegiatan Siswa" },
  { name: "Program Liburan Akhir Semester 2", category: "Kegiatan Siswa" },
  { name: "Seminar Kesehatan", category: "Kegiatan Siswa" },
  { name: "Seminar Anti NAFZA", category: "Kegiatan Siswa" },
  { name: "Seminar Anti Bullying", category: "Kegiatan Siswa" },
  { name: "Seminar Anti LGBT", category: "Kegiatan Siswa" },
  { name: "Seminar Kemandirian", category: "Kegiatan Siswa" },
  { name: "Seminar Kedisiplinan", category: "Kegiatan Siswa" },
  { name: "Seminar Anti Korupsi", category: "Kegiatan Siswa" },
  { name: "Eskpo Ekstrakulikuler", category: "Kegiatan Siswa" },
  { name: "Ekstrakulikuler Futsal", category: "Kegiatan Siswa" },
  { name: "Ekstrakulikuler Badminton", category: "Kegiatan Siswa" },
  { name: "Ekstrakulikuler Basket", category: "Kegiatan Siswa" },
  { name: "Ekstrakulikuler Panahan", category: "Kegiatan Siswa" },
  { name: "Ekstrakulikuler Berenang", category: "Kegiatan Siswa" },
  { name: "Buku Kerja Guru Kelas", category: "Penyusunan Dokumen" },
  { name: "Program Kerja Kelas", category: "Penyusunan Dokumen" },
  { name: "Bank Data Kelas", category: "Pengembangan Program" },
  { name: "Struktur Organisasi Kelas", category: "Pengembangan Program" },
  { name: "Tata Tertib Kelas", category: "Pengembangan Program" },
  { name: "Piket Kelas", category: "Pengembangan Program" },
  { name: "Menghias Kelas", category: "Pengembangan Program" },
  { name: "Pemilihan OSIS", category: "Pengembangan Program" },
  { name: "Pembentukan Struktur Organisasi OSIS", category: "Pengembangan Program" },
  { name: "Pelatihan & Pembinaan OSIS", category: "Pengembangan Program" },
  { name: "LDKS OSIS", category: "Kegiatan Siswa" },
  { name: "Silabus Krida", category: "Penyusunan Dokumen" },
  { name: "Buku Krida", category: "Pengembangan Program" },
  { name: "BKU & SKU", category: "Penyusunan Dokumen" },
  { name: "Pedoman Penilaian", category: "Penyusunan Dokumen" },
  { name: "Rencana Penilaian", category: "Penyusunan Dokumen" },
  { name: "Asesmen Diagnostik", category: "Pengembangan Program" },
  { name: "Penilaian Formatif", category: "Penyusunan Dokumen" },
  { name: "Penilaian Sumatif Tengah Semester Ganjil", category: "Pengembangan Program" },
  { name: "Penilaian Sumatif Akhir Semester", category: "Pengembangan Program" },
  { name: "Penilaian Sumatif Tengah Semester Genap", category: "Pengembangan Program" },
  { name: "Penilaian Sumatif Akhir Tahun", category: "Pengembangan Program" },
  { name: "Portofolio", category: "Pengembangan Program" },
  { name: "Penilaian Nonkognitif", category: "Pengembangan Program" },
  { name: "Asesmen Nasional (ANBK)", category: "Pengembangan Program" },
  { name: "TKA (Tes Kemampuan Akademik)", category: "Pengembangan Program" },
  { name: "Ujian Akhir Sekolah (UAS)", category: "Pengembangan Program" },
  { name: "Buku Nilai", category: "Pengembangan Program" },
  { name: "Laporan Nilai Tengah Semester Ganjil", category: "Penyusunan Dokumen" },
  { name: "Laporan Nilai Akhir Semester Ganjil", category: "Penyusunan Dokumen" },
  { name: "Laporan Nilai Tengah Semester Genap", category: "Penyusunan Dokumen" },
  { name: "Laporan Nilai Akhir Semester Genap", category: "Penyusunan Dokumen" },
  { name: "Ijazah", category: "Pengembangan Program" },
  { name: "Analisis Daya Serap", category: "Pengembangan Program" },
  { name: "Riset & Analisis", category: "Pengembangan Program" },
  { name: "Brand Strategy", category: "Pengembangan Program" },
  { name: "Strategi Pemasaran", category: "Penyusunan Dokumen" },
  { name: "Strategi Digital Marketing", category: "Penyusunan Dokumen" },
  { name: "Optimasi Channel Digital", category: "Pengembangan Program" },
  { name: "SMM (Social Media Marketing)", category: "Pengembangan Program" },
  { name: "WhatsApp Marketing", category: "Pengembangan Program" },
  { name: "LinkedIn Broadcast", category: "Pengembangan Program" },
  { name: "E-Mail Marketing", category: "Pengembangan Program" },
  { name: "SEO", category: "Pengembangan Program" },
  { name: "Google Ads", category: "Pengembangan Program" },
  { name: "Meta Ads", category: "Pengembangan Program" },
  { name: "Podcast", category: "Pengembangan Program" },
  { name: "Live", category: "Pengembangan Program" },
  { name: "Website", category: "Pengembangan Program" },
  { name: "Social Media Account", category: "Pengembangan Program" },
  { name: "Media Asset", category: "Pengembangan Program" },
  { name: "Brosur", category: "Pengembangan Program" },
  { name: "Poster A3", category: "Pengembangan Program" },
  { name: "Slide Presentasi", category: "Pengembangan Program" },
  { name: "Standing/Roll Banner", category: "Pengembangan Program" },
  { name: "Spanduk", category: "Pengadaan Sarpras" },
  { name: "Video Profil", category: "Pengembangan Program" },
  { name: "Sticker", category: "Pengembangan Program" },
  { name: "Nametag Panitia", category: "Pengembangan Program" },
  { name: "Folder Google Drive PPDB", category: "Pengembangan Program" },
  { name: "Pusat Informasi Digital PPDB", category: "Pengembangan Program" },
  { name: "Roadshow PPDB", category: "Sosialisasi" },
  { name: "Sebar Media Cetak", category: "Pengadaan Sarpras" },
  { name: "Liputan Sekolah oleh TV Nasional", category: "Pengembangan Program" },
  { name: "KOL (Key Opinion Leader) Tokoh", category: "Pengembangan Program" },
  { name: "Influencer Marketing", category: "Pengembangan Program" },
  { name: "Promo Harga (Diskon/Beasiswa/Jalur Khusus dll)", category: "Pengembangan Program" },
  { name: "Program Ayo Visit ke Sekolah: English Camp", category: "Pengembangan Program" },
  { name: "Program Ayo Visit ke Sekolah: Free Manasik", category: "Pengembangan Program" },
  { name: "Program Ayo Visit ke Sekolah: Fun Bercocok Tanam", category: "Pengembangan Program" },
  { name: "Program Ayo Visit ke Sekolah: Trial Mondok", category: "Pengembangan Program" },
  { name: "Strategi Penerimaan Pendaftaran", category: "Penyusunan Dokumen" },
  { name: "Penerimaan Pendaftaran", category: "Pengembangan Program" },
  { name: "Resepsionis", category: "Pengembangan Program" },
  { name: "Monev & Laporan PPDB", category: "Penyusunan Dokumen" },
  { name: "Analisis Kebutuhan GTK", category: "Pengembangan Program" },
  { name: "Pelaksanaan Rekrutmen", category: "Pengembangan Program" },
  { name: "Mutasi GTK", category: "Pengembangan Program" },
  { name: "Budaya Organisasi", category: "Pengembangan Program" },
  { name: "Tata Tertib GTK", category: "Pengembangan Program" },
  { name: "Kode Etik Guru", category: "Penyusunan Dokumen" },
  { name: "Sumpah Guru", category: "Penyusunan Dokumen" },
  { name: "Data Induk GTK", category: "Penyusunan Dokumen" },
  { name: "Pemberkesan GTK", category: "Pengembangan Program" },
  { name: "Pemenuhan GTK", category: "Pengadaan Sarpras" },
  { name: "Struktur Organisasi & Jobdesk", category: "Pengembangan Program" },
  { name: "Sistem Jenjang Karir", category: "Pengembangan Program" },
  { name: "Sistem Pendukung Kedinasan GTK", category: "Pengembangan Program" },
  { name: "Presensi GTK", category: "Pengembangan Program" },
  { name: "Uji Kompetensi Guru (UKG)", category: "Pengembangan Program" },
  { name: "Penilaian Kinerja Kepala Sekolah (PKKS)", category: "Pengembangan Program" },
  { name: "Penilaian Kinerja Guru (PKG)", category: "Pengembangan Program" },
  { name: "Evadir", category: "Pengembangan Program" },
  { name: "Peningkatan Kompetensi Berkelanjutan (PKB)", category: "Pengembangan Program" },
  { name: "Rapor Mutu Guru", category: "Penyusunan Dokumen" },
  { name: "Tes Psikologi Guru", category: "Pengembangan Program" },
  { name: "Pelatihan Kedinasan : Peningkatan Kompetensi KS", category: "Pengembangan Program" },
  { name: "Perencanaan Sarpras", category: "Pengembangan Program" },
  { name: "Administrasi Sarpras", category: "Penyusunan Dokumen" },
  { name: "Perencanaan Prasarana", category: "Pengembangan Program" },
  { name: "Penataan Prasarana", category: "Pengembangan Program" },
  { name: "Supervisi Prasarana", category: "Pengembangan Program" },
  { name: "Pemeliharaan Prasarana", category: "Pengembangan Program" },
  { name: "Pemenuhan Sarana Kelas", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Ruang BK", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Ruang Belajar & Membaca", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Ruang Ibadah & Halaqoh", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Laboratorium IPA", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Cooking Class Putri", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Perpustakaan", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Digital Classroom", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Lapangan Olahraga", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Lapangan Upacara", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Ruang Kesiswaan", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Aula Muhadharah", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Aula Bersama", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Asrama", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Kamar Mandi Asrama", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Ruang Laundry", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Ruang Pemanggilan", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Tempat Makan", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Kamar Musyrif", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Ruang UKS", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Kantor Manajemen", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Kantor Guru", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Ruang Tamu", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Kantin", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Gudang Logistik Habis Pakai", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Gudang Peralatan", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Gudang Mebeularian", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Gudang Bahan Dapur", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Dapur", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Ruang Laundry Putra", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Ruang Laundry Putri", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Ruang Panel", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Pos Security", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Area Parkiran", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Area Taman Sekolah", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana Jaringan", category: "Pengadaan Sarpras" },
  { name: "Pemenuhan Sarana CCTV", category: "Pengadaan Sarpras" },
  { name: "Layanan Kebersihan", category: "Pengembangan Program" },
  { name: "Hospitality Karyawan", category: "Pengembangan Program" },
  { name: "Pengadaan Buku", category: "Pengadaan Sarpras" },
  { name: "Pengadaan Seragam", category: "Pengadaan Sarpras" },
  { name: "Analisis Kebutuhan & Pemenuhan Ruang", category: "Pengembangan Program" },
  { name: "Pemeliharaan Bangunan", category: "Pengembangan Program" },
  { name: "Teknologi Pendukung Pembelajaran", category: "Pengembangan Program" },
  { name: "Teknologi Pendukung Sistem Manajemen", category: "Pengembangan Program" },
  { name: "Teknologi Pendukung Komunikasi", category: "Pengembangan Program" },
  { name: "Teknologi Pendukung Proyek Kegiatan", category: "Pengembangan Program" },
  { name: "Teknologi Pendukung File Digital", category: "Pengembangan Program" },
  { name: "Teknologi Pendukung Kantin", category: "Pengembangan Program" },
  { name: "Lingkungan Sekolah Edukatif, Nyaman & Aman", category: "Pengembangan Program" },
  { name: "Lingkungan Kelas Edukatif, Nyaman & Aman", category: "Pengembangan Program" },
  { name: "Analisis Kebutuhan & Pemenuhan Kelistrikan", category: "Pengadaan Sarpras" },
  { name: "Pemeliharaan Kelistrikan", category: "Pengembangan Program" },
  { name: "Sistem manajemen file dan kearsipan", category: "Pengembangan Program" },
  { name: "Sistem persuratan", category: "Pengembangan Program" },
  { name: "Penerimaan Tamu", category: "Pengembangan Program" },
  { name: "Data Induk Peserta Didik", category: "Penyusunan Dokumen" },
  { name: "Pemberkasan Peserta Didik", category: "Penyusunan Dokumen" },
  { name: "Buku Induk Peserta Didik", category: "Penyusunan Dokumen" },
  { name: "Pemotretan Peserta Didik", category: "Pengembangan Program" },
  { name: "Mutasi Peserta Didik", category: "Pengembangan Program" },
  { name: "Pengolahan Ijazah", category: "Pengembangan Program" },
  { name: "Pusat Informasi Digital", category: "Pengembangan Program" },
  { name: "Papan Pusat Informasi untuk Guru", category: "Pengembangan Program" },
  { name: "Papan Pusat Informasi untuk Manajemen", category: "Pengembangan Program" },
  { name: "Papan Statistik Sekolah", category: "Pengembangan Program" },
  { name: "SIM Digital", category: "Pengembangan Program" },
  { name: "Data Periodik Dapodik", category: "Pengembangan Program" },
  { name: "Laporan Dapodik", category: "Penyusunan Dokumen" },
  { name: "NUPTK", category: "Pengembangan Program" },
  { name: "Akun Belajar.id", category: "Pengembangan Program" },
  { name: "Legalitas Sekolah", category: "Penyusunan Dokumen" },
  { name: "Izin Operasional SMA", category: "Pengembangan Program" },
  { name: "Legalitas Yayasan", category: "Penyusunan Dokumen" },
  { name: "Legalitas Kepala Sekolah", category: "Penyusunan Dokumen" },
  { name: "Akreditasi", category: "Penyusunan Dokumen" },
  { name: "PBD & Rapor Pendidikan", category: "Pengembangan Program" },
  { name: "Evaluasi Diri Sekolah (EDS)", category: "Pengembangan Program" },
  { name: "Pengembangan Visi, Misi, Tujuan, & Strategi", category: "Pengembangan Program" },
  { name: "Pengembangan Struktur Organisasi", category: "Pengembangan Program" },
  { name: "Pengembangan RKJM", category: "Pengembangan Program" },
  { name: "Pengembangan RKT", category: "Pengembangan Program" },
  { name: "Pengembangan RAPBS", category: "Pengembangan Program" },
  { name: "Pengembangan Program Kerja", category: "Pengembangan Program" },
  { name: "Rapat Kerja Awal Tahun Pelajaran", category: "Forum/Rapat" },
  { name: "Rapat Kerja Pertengahan Tahun Pelajaran", category: "Forum/Rapat" },
  { name: "Rapat Evaluasi Pekanan", category: "Forum/Rapat" },
  { name: "Rapat Kerja K3S", category: "Forum/Rapat" },
  { name: "Rapat Dinas Rutin Kepala Sekolah", category: "Forum/Rapat" },
  { name: "Rapat Dinas Rutin Operator", category: "Forum/Rapat" },
  { name: "Buku Induk Pedoman Sekolah", category: "Penyusunan Dokumen" },
  { name: "Buku Induk SOP Sekolah", category: "Penyusunan Dokumen" },
  { name: "Supervisi Akademik", category: "Pengembangan Program" },
  { name: "Supervisi Nonakademik", category: "Pengembangan Program" },
  { name: "Kalender Kerja", category: "Penyusunan Dokumen" },
  { name: "Scheduling", category: "Pengembangan Program" },
  { name: "Manajemen Performa & Sistem Evaluasi", category: "Pengembangan Program" },
  { name: "Refleksi", category: "Pengembangan Program" },
  { name: "Supervisi Jabar Beraksi", category: "Pengembangan Program" },
  { name: "Pedoman Keuangan", category: "Penyusunan Dokumen" },
  { name: "Sistem Penggajian", category: "Pengembangan Program" },
  { name: "Strategi Keuangan", category: "Penyusunan Dokumen" },
  { name: "RAPBS", category: "Penyusunan Dokumen" },
  { name: "Cashflow Jangka Panjang", category: "Penyusunan Dokumen" },
  { name: "Biaya Pendidikan", category: "Pengembangan Program" },
  { name: "Pembukuan Keuangan", category: "Penyusunan Dokumen" },
  { name: "Penagihan", category: "Pengembangan Program" },
  { name: "Layanan Kasbon Pegawai", category: "Pengembangan Program" },
  { name: "Diskon Pendidikan", category: "Pengembangan Program" },
  { name: "Audit Internal Keuangan", category: "Pengembangan Program" },
  { name: "Laporan Keuangan Bulanan", category: "Penyusunan Dokumen" },
  { name: "Laporan Keuangan Tahunan", category: "Penyusunan Dokumen" },
  { name: "RAKS", category: "Pengembangan Program" },
  { name: "Pembukuan", category: "Penyusunan Dokumen" },
  { name: "Laporan", category: "Penyusunan Dokumen" },
  { name: "Monev", category: "Penyusunan Dokumen" },
  { name: "Rekonsoloiasi", category: "Penyusunan Dokumen" },
  { name: "IBC (Internet Banking Corporate)", category: "Pengembangan Program" },
  { name: "Pengembangan Buku Matematika Inovatif", category: "Pengembangan Program" },
  { name: "Program Integrasi Mutu Layanan Santri", category: "Pengembangan Program" },
  { name: "Program Dashboard Kinerja Terpadu Pesantren", category: "Pengembangan Program" },
  { name: "Program Survei Kepuasan Santri & Wali Santri Terintegrasi", category: "Pengembangan Program" },
  { name: "Program Gerakan Dapur Aman, Sehat & Efisien", category: "Pengembangan Program" },
  { name: "Program Zero Lost Learning Time", category: "Pengembangan Program" },
  { name: "Program Pengembangan Kompetensi GTK Berbasis Kinerja", category: "Pengembangan Program" },
  { name: "Program Perbaikan Siklus Program: Rencana–Laksana–Evaluasi–RTL", category: "Pengembangan Program" },
  { name: "Program Efisiensi Anggaran Berbasis Layanan Prioritas Santri", category: "Pengembangan Program" },
  { name: "Program Transformasi Digital Administrasi & Layanan", category: "Penyusunan Dokumen" },
  { name: "Program Budaya Disiplin & Pembiasaan Positif Santri", category: "Pengembangan Program" },
  { name: "Program Kesehatan Preventif Santri", category: "Pengembangan Program" },
  { name: "Program Keamanan & Keselamatan Pesantren", category: "Kegiatan Siswa" },
  { name: "Program Satu Data Pesantren", category: "Pengembangan Program" },
  { name: "Program Inovasi Pembelajaran & Budaya Digital", category: "Pengembangan Program" },
  { name: "Program Kemitraan & Reputasi Lembaga", category: "Pengembangan Program" },
];

async function run() {
  console.log('--- Assigning categories to rips_programs ---');

  // 1. Fetch all categories
  const categories = await db('rips_program_categories').select('*');
  const catMap = new Map();
  for (const c of categories) {
    catMap.set(c.name.trim().toLowerCase(), c.id);
  }

  // Ensure default categories exist
  const defaultCats = [
    { name: 'Pengembangan Program', color: '#2563EB', bg_color: '#EFF6FF', border_color: '#BFDBFE' },
    { name: 'Penyusunan Dokumen', color: '#7C3AED', bg_color: '#F5F3FF', border_color: '#DDD6FE' },
    { name: 'Pengadaan Sarpras', color: '#D97706', bg_color: '#FFFBEB', border_color: '#FDE68A' },
    { name: 'Kegiatan Siswa', color: '#059669', bg_color: '#ECFDF5', border_color: '#A7F3D0' },
    { name: 'Forum/Rapat', color: '#DC2626', bg_color: '#FEF2F2', border_color: '#FECACA' },
    { name: 'Sosialisasi', color: '#0891B2', bg_color: '#ECFEFF', border_color: '#A5F3FC' },
  ];

  for (const dc of defaultCats) {
    if (!catMap.has(dc.name.toLowerCase())) {
      const [newId] = await db('rips_program_categories').insert({
        name: dc.name,
        color: dc.color,
        bg_color: dc.bg_color,
        border_color: dc.border_color,
        is_active: true,
        created_at: db.fn.now(),
        updated_at: db.fn.now(),
      });
      catMap.set(dc.name.toLowerCase(), newId);
    }
  }

  let updatedCount = 0;
  for (const item of mappingData) {
    const catId = catMap.get(item.category.trim().toLowerCase());
    if (catId) {
      const updated = await db('rips_programs')
        .whereRaw('LOWER(TRIM(name)) = ?', [item.name.trim().toLowerCase()])
        .update({
          category_id: catId,
          updated_at: db.fn.now(),
        });
      updatedCount += updated;
    } else {
      console.warn(`Category not found for: ${item.category}`);
    }
  }

  console.log(`Successfully updated ${updatedCount} program records with assigned categories.`);
  process.exit(0);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
