const db = require('../src/config/db/manajemen');

const rawData = [
  // MANAJEMEN STRATEGIS
  {
    bidang: 'MANAJEMEN STRATEGIS',
    bidangCode: 'BID-01',
    subbidang: 'Tim Pengembang Sekolah (TPS)',
    sasaran: 'Pengembangan sekolah berjalan terkoordinasi, berbasis data, dan menghasilkan tindak lanjut yang nyata.',
    indikator: 'Persentase agenda kerja TPS yang terlaksana sesuai rencana',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Process/Service',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'MANAJEMEN STRATEGIS',
    bidangCode: 'BID-01',
    subbidang: 'Tim Pengembang Sekolah (TPS)',
    sasaran: 'Pengembangan sekolah berjalan terkoordinasi, berbasis data, dan menghasilkan tindak lanjut yang nyata.',
    indikator: 'Persentase rekomendasi TPS yang ditindaklanjuti',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '>= 85%',
    baseline: 0,
    targetVal: 85,
    satuan: '%'
  },
  {
    bidang: 'MANAJEMEN STRATEGIS',
    bidangCode: 'BID-01',
    subbidang: 'Tim Pengembang Sekolah (TPS)',
    sasaran: 'Pengembangan sekolah berjalan terkoordinasi, berbasis data, dan menghasilkan tindak lanjut yang nyata.',
    indikator: 'Jumlah keputusan/produk pengembangan sekolah yang terdokumentasi',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '>= 6/tahun',
    baseline: 0,
    targetVal: 6,
    satuan: 'dokumen'
  },
  {
    bidang: 'MANAJEMEN STRATEGIS',
    bidangCode: 'BID-01',
    subbidang: 'Analisis & Riset',
    sasaran: 'Pengambilan keputusan sekolah menggunakan data yang relevan, aktual, dan ditindaklanjuti.',
    indikator: 'Persentase agenda analisis prioritas yang selesai tepat waktu',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Process/Service',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'MANAJEMEN STRATEGIS',
    bidangCode: 'BID-01',
    subbidang: 'Analisis & Riset',
    sasaran: 'Pengambilan keputusan sekolah menggunakan data yang relevan, aktual, dan ditindaklanjuti.',
    indikator: 'Persentase rekomendasi berbasis data yang masuk ke rencana kerja',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '>= 80%',
    baseline: 0,
    targetVal: 80,
    satuan: '%'
  },
  {
    bidang: 'MANAJEMEN STRATEGIS',
    bidangCode: 'BID-01',
    subbidang: 'Analisis & Riset',
    sasaran: 'Pengambilan keputusan sekolah menggunakan data yang relevan, aktual, dan ditindaklanjuti.',
    indikator: 'Jumlah studi/analisis strategis yang menghasilkan rekomendasi',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '>= 4/tahun',
    baseline: 0,
    targetVal: 4,
    satuan: 'studi'
  },
  {
    bidang: 'MANAJEMEN STRATEGIS',
    bidangCode: 'BID-01',
    subbidang: 'Rencana Strategis',
    sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.',
    indikator: 'Persentase dokumen perencanaan wajib yang tersedia dan berlaku',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'MANAJEMEN STRATEGIS',
    bidangCode: 'BID-01',
    subbidang: 'Rencana Strategis',
    sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.',
    indikator: 'Persentase program tahunan yang memiliki keterkaitan dengan sasaran strategis',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'MANAJEMEN STRATEGIS',
    bidangCode: 'BID-01',
    subbidang: 'Rencana Strategis',
    sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.',
    indikator: 'Persentase sasaran strategis yang memiliki indikator dan target',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },

  // AKADEMIK
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'SKL (Standar Kompetensi Lulusan)',
    sasaran: 'Kompetensi lulusan pada aspek sikap, pengetahuan, dan keterampilan mencapai target sekolah.',
    indikator: 'Persentase lulusan mencapai target kompetensi sikap',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'SKL (Standar Kompetensi Lulusan)',
    sasaran: 'Kompetensi lulusan pada aspek sikap, pengetahuan, dan keterampilan mencapai target sekolah.',
    indikator: 'Persentase lulusan mencapai target kompetensi pengetahuan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'SKL (Standar Kompetensi Lulusan)',
    sasaran: 'Kompetensi lulusan pada aspek sikap, pengetahuan, dan keterampilan mencapai target sekolah.',
    indikator: 'Persentase lulusan mencapai target kompetensi keterampilan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'SKL (Standar Kompetensi Lulusan)',
    sasaran: 'Kompetensi lulusan pada aspek sikap, pengetahuan, dan keterampilan mencapai target sekolah.',
    indikator: 'Rata-rata nilai capaian kompetensi lulusan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Outcome',
    targetRaw: '>= 75 poin',
    baseline: 0,
    targetVal: 75,
    satuan: 'poin'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Standar Isi',
    sasaran: 'Kurikulum dan perangkat pembelajaran selaras dengan profil lulusan, kebutuhan santri, dan ketentuan yang berlaku.',
    indikator: 'Persentase dokumen kurikulum yang diperbarui tepat waktu',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Standar Isi',
    sasaran: 'Kurikulum dan perangkat pembelajaran selaras dengan profil lulusan, kebutuhan santri, dan ketentuan yang berlaku.',
    indikator: 'Persentase mata pelajaran/program yang memiliki perangkat pembelajaran lengkap',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Standar Isi',
    sasaran: 'Kurikulum dan perangkat pembelajaran selaras dengan profil lulusan, kebutuhan santri, dan ketentuan yang berlaku.',
    indikator: 'Persentase struktur kurikulum yang terlaksana sesuai alokasi',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Intrakulikuler',
    sasaran: 'Proses pembelajaran reguler terlaksana efektif, terencana, dan terpantau.',
    indikator: 'Persentase jam pembelajaran yang terlaksana',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 97%',
    baseline: 0,
    targetVal: 97,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Intrakulikuler',
    sasaran: 'Proses pembelajaran reguler terlaksana efektif, terencana, dan terpantau.',
    indikator: 'Persentase kelas yang memiliki perencanaan pembelajaran lengkap',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Intrakulikuler',
    sasaran: 'Proses pembelajaran reguler terlaksana efektif, terencana, dan terpantau.',
    indikator: 'Persentase hasil supervisi pembelajaran memenuhi standar',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Intrakulikuler',
    sasaran: 'Proses pembelajaran reguler terlaksana efektif, terencana, dan terpantau.',
    indikator: 'Rata-rata kehadiran santri pada pembelajaran',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Kokulikuler',
    sasaran: 'Kegiatan kokurikuler memperkuat pembelajaran dan pengembangan kompetensi santri secara terarah.',
    indikator: 'Persentase program kokurikuler terlaksana sesuai kalender',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Process/Service',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Kokulikuler',
    sasaran: 'Kegiatan kokurikuler memperkuat pembelajaran dan pengembangan kompetensi santri secara terarah.',
    indikator: 'Persentase keikutsertaan santri dalam kegiatan kokurikuler',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Kokulikuler',
    sasaran: 'Kegiatan kokurikuler memperkuat pembelajaran dan pengembangan kompetensi santri secara terarah.',
    indikator: 'Persentase kegiatan kokurikuler yang memiliki evaluasi dan tindak lanjut',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: "Program Unggulan Al-Qur'an",
    sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten.",
    indikator: 'Persentase santri mencapai target kompetensi program',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 85%',
    baseline: 0,
    targetVal: 85,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: "Program Unggulan Al-Qur'an",
    sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten.",
    indikator: 'Persentase sesi pembelajaran/program terlaksana sesuai jadwal',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Process/Service',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: "Program Unggulan Al-Qur'an",
    sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten.",
    indikator: 'Rata-rata capaian asesmen program',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Outcome',
    targetRaw: '>= 80%',
    baseline: 0,
    targetVal: 80,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: "Program Unggulan Al-Qur'an",
    sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten.",
    indikator: 'Persentase peserta yang menyelesaikan program',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Program Unggulan Bahasa',
    sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.',
    indikator: 'Persentase santri mencapai target kompetensi program',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 85%',
    baseline: 0,
    targetVal: 85,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Program Unggulan Bahasa',
    sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.',
    indikator: 'Persentase sesi pembelajaran/program terlaksana sesuai jadwal',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Process/Service',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Program Unggulan Bahasa',
    sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.',
    indikator: 'Rata-rata capaian asesmen program',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Outcome',
    targetRaw: '>= 80%',
    baseline: 0,
    targetVal: 80,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Program Unggulan Bahasa',
    sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.',
    indikator: 'Persentase peserta yang menyelesaikan program',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Program Unggulan Kewirausahaan',
    sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.',
    indikator: 'Persentase santri mencapai target kompetensi program',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 85%',
    baseline: 0,
    targetVal: 85,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Program Unggulan Kewirausahaan',
    sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.',
    indikator: 'Persentase sesi pembelajaran/program terlaksana sesuai jadwal',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Process/Service',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Program Unggulan Kewirausahaan',
    sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.',
    indikator: 'Rata-rata capaian asesmen program',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Outcome',
    targetRaw: '>= 80%',
    baseline: 0,
    targetVal: 80,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Program Unggulan Kewirausahaan',
    sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.',
    indikator: 'Persentase peserta yang menyelesaikan program',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Program Unggulan IT',
    sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.',
    indikator: 'Persentase santri mencapai target kompetensi program',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 85%',
    baseline: 0,
    targetVal: 85,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Program Unggulan IT',
    sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.',
    indikator: 'Persentase sesi pembelajaran/program terlaksana sesuai jadwal',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Process/Service',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Program Unggulan IT',
    sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.',
    indikator: 'Rata-rata capaian asesmen program',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Outcome',
    targetRaw: '>= 80%',
    baseline: 0,
    targetVal: 80,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Program Unggulan IT',
    sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.',
    indikator: 'Persentase peserta yang menyelesaikan program',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Psikoedukasi',
    sasaran: 'Santri memperoleh dukungan psikologis, sosial, dan pencegahan masalah secara terukur.',
    indikator: 'Persentase santri sasaran yang mendapat layanan skrining/asesmen',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Psikoedukasi',
    sasaran: 'Santri memperoleh dukungan psikologis, sosial, dan pencegahan masalah secara terukur.',
    indikator: 'Persentase kasus prioritas yang ditindaklanjuti sesuai SLA',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Psikoedukasi',
    sasaran: 'Santri memperoleh dukungan psikologis, sosial, dan pencegahan masalah secara terukur.',
    indikator: 'Rata-rata skor kepuasan santri terhadap layanan BK',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Outcome',
    targetRaw: '>= 4/5',
    baseline: 0,
    targetVal: 80, // 4/5 = 80%
    satuan: 'skor (1-5)'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Psikoedukasi',
    sasaran: 'Santri memperoleh dukungan psikologis, sosial, dan pencegahan masalah secara terukur.',
    indikator: 'Jumlah insiden bullying terverifikasi per 100 santri',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Process/Service',
    targetRaw: '<= 2 kasus/100 santri',
    baseline: 0,
    targetVal: 2,
    satuan: 'kasus/100 santri'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Kesiswaan',
    sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.',
    indikator: 'Persentase program kesiswaan terlaksana sesuai rencana',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Process/Service',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Kesiswaan',
    sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.',
    indikator: 'Persentase kehadiran santri pada kegiatan wajib',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Kesiswaan',
    sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.',
    indikator: 'Persentase pelanggaran tata tertib yang ditindaklanjuti sesuai prosedur',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Kesiswaan',
    sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.',
    indikator: 'Tingkat penyelesaian kasus pembinaan santri',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Keasramaan',
    sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.',
    indikator: 'Persentase kepatuhan jadwal wajib asrama',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Process/Service',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Keasramaan',
    sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.',
    indikator: 'Persentase kehadiran santri pada kegiatan ibadah wajib terpantau',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Keasramaan',
    sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.',
    indikator: 'Jumlah pelanggaran tata tertib asrama per 100 santri',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '<= 2 kasus/100 santri',
    baseline: 0,
    targetVal: 2,
    satuan: 'kasus/100 santri'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Keasramaan',
    sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.',
    indikator: 'Persentase kamar/area asrama memenuhi standar kebersihan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Bina Prestasi',
    sasaran: 'Potensi dan prestasi santri teridentifikasi, dibina, dan menghasilkan capaian kompetitif.',
    indikator: 'Persentase santri berbakat yang teridentifikasi dan memiliki peta pembinaan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Bina Prestasi',
    sasaran: 'Potensi dan prestasi santri teridentifikasi, dibina, dan menghasilkan capaian kompetitif.',
    indikator: 'Persentase program pembinaan prestasi terlaksana',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Process/Service',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Bina Prestasi',
    sasaran: 'Potensi dan prestasi santri teridentifikasi, dibina, dan menghasilkan capaian kompetitif.',
    indikator: 'Jumlah kejuaraan/prestasi yang diraih',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 5 prestasi/tahun',
    baseline: 0,
    targetVal: 5,
    satuan: 'prestasi'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Bina Prestasi',
    sasaran: 'Potensi dan prestasi santri teridentifikasi, dibina, dan menghasilkan capaian kompetitif.',
    indikator: 'Persentase peserta bina prestasi yang mencapai target kompetensi',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 75%',
    baseline: 0,
    targetVal: 75,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Pendidikan Karakter & Integratif',
    sasaran: 'Karakter, kecakapan hidup, dan pembiasaan positif santri berkembang melalui program yang konsisten.',
    indikator: 'Persentase santri mencapai target indikator karakter',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Pendidikan Karakter & Integratif',
    sasaran: 'Karakter, kecakapan hidup, dan pembiasaan positif santri berkembang melalui program yang konsisten.',
    indikator: 'Persentase pelaksanaan pembiasaan harian sesuai standar',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Pendidikan Karakter & Integratif',
    sasaran: 'Karakter, kecakapan hidup, dan pembiasaan positif santri berkembang melalui program yang konsisten.',
    indikator: 'Rata-rata skor hasil survei budaya/karakter sekolah',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Outcome',
    targetRaw: '>= 4/5',
    baseline: 0,
    targetVal: 80,
    satuan: 'skor (1-5)'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Ekstrakulikuler',
    sasaran: 'Program ekstrakurikuler tersedia sesuai minat santri, berjalan aktif, dan menghasilkan perkembangan kompetensi.',
    indikator: 'Persentase ekstrakurikuler yang aktif sesuai kalender',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Ekstrakulikuler',
    sasaran: 'Program ekstrakurikuler tersedia sesuai minat santri, berjalan aktif, dan menghasilkan perkembangan kompetensi.',
    indikator: 'Persentase santri mengikuti minimal satu ekstrakurikuler',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 85%',
    baseline: 0,
    targetVal: 85,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Ekstrakulikuler',
    sasaran: 'Program ekstrakurikuler tersedia sesuai minat santri, berjalan aktif, dan menghasilkan perkembangan kompetensi.',
    indikator: 'Persentase sesi ekstrakurikuler terlaksana',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Process/Service',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Ekstrakulikuler',
    sasaran: 'Program ekstrakurikuler tersedia sesuai minat santri, berjalan aktif, dan menghasilkan perkembangan kompetensi.',
    indikator: 'Persentase ekskul yang memiliki evaluasi kompetensi peserta',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Manajemen Kelas',
    sasaran: 'Pengelolaan kelas mendukung pembelajaran yang tertib, nyaman, aman, dan partisipatif.',
    indikator: 'Persentase kelas yang memenuhi checklist manajemen kelas',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Manajemen Kelas',
    sasaran: 'Pengelolaan kelas mendukung pembelajaran yang tertib, nyaman, aman, dan partisipatif.',
    indikator: 'Persentase kehadiran santri di kelas',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Manajemen Kelas',
    sasaran: 'Pengelolaan kelas mendukung pembelajaran yang tertib, nyaman, aman, dan partisipatif.',
    indikator: 'Jumlah insiden gangguan pembelajaran per 100 jam pelajaran',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '<= 2 kasus/100 santri',
    baseline: 0,
    targetVal: 2,
    satuan: 'insiden/100 jam'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'OSIS',
    sasaran: 'Organisasi santri berjalan aktif, tertib, dan menjadi wahana kepemimpinan serta tanggung jawab.',
    indikator: 'Persentase program OSIS terlaksana',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Process/Service',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'OSIS',
    sasaran: 'Organisasi santri berjalan aktif, tertib, dan menjadi wahana kepemimpinan serta tanggung jawab.',
    indikator: 'Persentase posisi kepengurusan terisi dan memiliki jobdesk',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'OSIS',
    sasaran: 'Organisasi santri berjalan aktif, tertib, dan menjadi wahana kepemimpinan serta tanggung jawab.',
    indikator: 'Persentase pengurus mengikuti pelatihan kepemimpinan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Krida (Pramuka, PASKIBRA, PMR & Kesemaptaan)',
    sasaran: 'Program pembinaan kedisiplinan, kebugaran, kepemimpinan, dan keterampilan khusus santri berjalan terukur.',
    indikator: 'Persentase sesi latihan terlaksana sesuai program',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Process/Service',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Krida (Pramuka, PASKIBRA, PMR & Kesemaptaan)',
    sasaran: 'Program pembinaan kedisiplinan, kebugaran, kepemimpinan, dan keterampilan khusus santri berjalan terukur.',
    indikator: 'Persentase anggota mencapai standar kompetensi krida',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 80%',
    baseline: 0,
    targetVal: 80,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Krida (Pramuka, PASKIBRA, PMR & Kesemaptaan)',
    sasaran: 'Program pembinaan kedisiplinan, kebugaran, kepemimpinan, dan keterampilan khusus santri berjalan terukur.',
    indikator: 'Persentase anggota hadir aktif dalam latihan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Standar Penilaian',
    sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.',
    indikator: 'Persentase guru melaksanakan penilaian sesuai rencana',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Standar Penilaian',
    sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.',
    indikator: 'Persentase mata pelajaran memiliki instrumen penilaian lengkap',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Standar Penilaian',
    sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.',
    indikator: 'Persentase nilai tersampaikan tepat waktu',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'AKADEMIK',
    bidangCode: 'BID-02',
    subbidang: 'Standar Penilaian',
    sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.',
    indikator: 'Persentase hasil penilaian yang memiliki tindak lanjut',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },

  // PPDB & PEMASARAN SEKOLAH
  {
    bidang: 'PPDB & PEMASARAN SEKOLAH',
    bidangCode: 'BID-03',
    subbidang: 'Strategi Pemasaran',
    sasaran: 'Strategi pemasaran berbasis data meningkatkan jangkauan, minat, dan konversi calon peserta didik.',
    indikator: 'Jumlah lead/calon santri potensial yang teridentifikasi',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 80%',
    baseline: 0,
    targetVal: 80,
    satuan: 'lead'
  },
  {
    bidang: 'PPDB & PEMASARAN SEKOLAH',
    bidangCode: 'BID-03',
    subbidang: 'Strategi Pemasaran',
    sasaran: 'Strategi pemasaran berbasis data meningkatkan jangkauan, minat, dan konversi calon peserta didik.',
    indikator: 'Conversion rate prospek menjadi pendaftar',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Outcome',
    targetRaw: '>= 80%',
    baseline: 0,
    targetVal: 80,
    satuan: '%'
  },
  {
    bidang: 'PPDB & PEMASARAN SEKOLAH',
    bidangCode: 'BID-03',
    subbidang: 'Strategi Pemasaran',
    sasaran: 'Strategi pemasaran berbasis data meningkatkan jangkauan, minat, dan konversi calon peserta didik.',
    indikator: 'Cost per lead',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '<= 2 kasus/100 santri',
    baseline: 0,
    targetVal: 50000,
    satuan: 'Rp/lead'
  },
  {
    bidang: 'PPDB & PEMASARAN SEKOLAH',
    bidangCode: 'BID-03',
    subbidang: 'Digital Marketing',
    sasaran: 'Saluran digital sekolah/pesantren aktif, konsisten, dan efektif menghasilkan jangkauan serta konversi.',
    indikator: 'Pertumbuhan jangkauan kanal digital',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 5%',
    baseline: 0,
    targetVal: 5,
    satuan: '%'
  },
  {
    bidang: 'PPDB & PEMASARAN SEKOLAH',
    bidangCode: 'BID-03',
    subbidang: 'Digital Marketing',
    sasaran: 'Saluran digital sekolah/pesantren aktif, konsisten, dan efektif menghasilkan jangkauan serta konversi.',
    indikator: 'Engagement rate konten',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 3%',
    baseline: 0,
    targetVal: 3,
    satuan: '%'
  },
  {
    bidang: 'PPDB & PEMASARAN SEKOLAH',
    bidangCode: 'BID-03',
    subbidang: 'Digital Marketing',
    sasaran: 'Saluran digital sekolah/pesantren aktif, konsisten, dan efektif menghasilkan jangkauan serta konversi.',
    indikator: 'Persentase lead PPDB dari kanal digital',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 50%',
    baseline: 0,
    targetVal: 50,
    satuan: '%'
  },
  {
    bidang: 'PPDB & PEMASARAN SEKOLAH',
    bidangCode: 'BID-03',
    subbidang: 'Marketing Tools',
    sasaran: 'Perangkat pemasaran tersedia, konsisten, mutakhir, dan mudah digunakan oleh tim.',
    indikator: 'Persentase aset marketing yang tersedia sesuai kebutuhan',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'PPDB & PEMASARAN SEKOLAH',
    bidangCode: 'BID-03',
    subbidang: 'Marketing Tools',
    sasaran: 'Perangkat pemasaran tersedia, konsisten, mutakhir, dan mudah digunakan oleh tim.',
    indikator: 'Persentase aset dengan informasi/branding terbaru',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'PPDB & PEMASARAN SEKOLAH',
    bidangCode: 'BID-03',
    subbidang: 'Marketing Tools',
    sasaran: 'Perangkat pemasaran tersedia, konsisten, mutakhir, dan mudah digunakan oleh tim.',
    indikator: 'Waktu rata-rata penyelesaian permintaan aset marketing',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '<= 3 hari',
    baseline: 0,
    targetVal: 3,
    satuan: 'hari'
  },
  {
    bidang: 'PPDB & PEMASARAN SEKOLAH',
    bidangCode: 'BID-03',
    subbidang: 'Offline Marketing',
    sasaran: 'Aktivitas pemasaran luring menjangkau target calon santri secara efektif dan terdokumentasi.',
    indikator: 'Jumlah aktivitas promosi luring terlaksana',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 80%',
    baseline: 0,
    targetVal: 10,
    satuan: 'kegiatan'
  },
  {
    bidang: 'PPDB & PEMASARAN SEKOLAH',
    bidangCode: 'BID-03',
    subbidang: 'Offline Marketing',
    sasaran: 'Aktivitas pemasaran luring menjangkau target calon santri secara efektif dan terdokumentasi.',
    indikator: 'Jumlah lead yang diperoleh dari aktivitas luring',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 80%',
    baseline: 0,
    targetVal: 80,
    satuan: 'lead'
  },
  {
    bidang: 'PPDB & PEMASARAN SEKOLAH',
    bidangCode: 'BID-03',
    subbidang: 'Offline Marketing',
    sasaran: 'Aktivitas pemasaran luring menjangkau target calon santri secara efektif dan terdokumentasi.',
    indikator: 'Conversion rate lead luring menjadi pendaftar',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Outcome',
    targetRaw: '>= 80%',
    baseline: 0,
    targetVal: 80,
    satuan: '%'
  },
  {
    bidang: 'PPDB & PEMASARAN SEKOLAH',
    bidangCode: 'BID-03',
    subbidang: 'Penerimaan Pendaftaran',
    sasaran: 'Proses penerimaan peserta didik baru berjalan cepat, transparan, akurat, dan mencapai target kuota.',
    indikator: 'Persentase pendaftar yang datanya lengkap dan tervalidasi',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'PPDB & PEMASARAN SEKOLAH',
    bidangCode: 'BID-03',
    subbidang: 'Penerimaan Pendaftaran',
    sasaran: 'Proses penerimaan peserta didik baru berjalan cepat, transparan, akurat, dan mencapai target kuota.',
    indikator: 'Waktu rata-rata respons awal calon pendaftar',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Process/Service',
    targetRaw: '<= 30 menit',
    baseline: 0,
    targetVal: 30,
    satuan: 'menit'
  },
  {
    bidang: 'PPDB & PEMASARAN SEKOLAH',
    bidangCode: 'BID-03',
    subbidang: 'Penerimaan Pendaftaran',
    sasaran: 'Proses penerimaan peserta didik baru berjalan cepat, transparan, akurat, dan mencapai target kuota.',
    indikator: 'Conversion rate pendaftar menjadi daftar ulang',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Outcome',
    targetRaw: '>= 85%',
    baseline: 0,
    targetVal: 85,
    satuan: '%'
  },
  {
    bidang: 'PPDB & PEMASARAN SEKOLAH',
    bidangCode: 'BID-03',
    subbidang: 'Penerimaan Pendaftaran',
    sasaran: 'Proses penerimaan peserta didik baru berjalan cepat, transparan, akurat, dan mencapai target kuota.',
    indikator: 'Persentase kuota terpenuhi',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },

  // SDM
  {
    bidang: 'SDM',
    bidangCode: 'BID-04',
    subbidang: 'Rekrutment & Mutasi',
    sasaran: 'Kebutuhan GTK terpenuhi dengan orang yang sesuai kompetensi, waktu, dan struktur organisasi.',
    indikator: 'Persentase posisi GTK prioritas terisi sesuai kebutuhan',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'SDM',
    bidangCode: 'BID-04',
    subbidang: 'Rekrutment & Mutasi',
    sasaran: 'Kebutuhan GTK terpenuhi dengan orang yang sesuai kompetensi, waktu, dan struktur organisasi.',
    indikator: 'Time to fill posisi prioritas',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '<= 2 hari',
    baseline: 0,
    targetVal: 14, // 14 hari
    satuan: 'hari'
  },
  {
    bidang: 'SDM',
    bidangCode: 'BID-04',
    subbidang: 'Rekrutment & Mutasi',
    sasaran: 'Kebutuhan GTK terpenuhi dengan orang yang sesuai kompetensi, waktu, dan struktur organisasi.',
    indikator: 'Persentase kandidat diterima memenuhi kriteria kompetensi',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'SDM',
    bidangCode: 'BID-04',
    subbidang: 'Pedoman GTK',
    sasaran: 'Tata kelola GTK memiliki aturan, standar perilaku, dan pedoman kerja yang jelas serta diterapkan.',
    indikator: 'Persentase pedoman GTK wajib yang tersedia dan berlaku',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'SDM',
    bidangCode: 'BID-04',
    subbidang: 'Pedoman GTK',
    sasaran: 'Tata kelola GTK memiliki aturan, standar perilaku, dan pedoman kerja yang jelas serta diterapkan.',
    indikator: 'Persentase GTK yang telah menerima/sosialisasi pedoman',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'SDM',
    bidangCode: 'BID-04',
    subbidang: 'Pedoman GTK',
    sasaran: 'Tata kelola GTK memiliki aturan, standar perilaku, dan pedoman kerja yang jelas serta diterapkan.',
    indikator: 'Persentase pelanggaran SOP/etik yang ditindaklanjuti sesuai prosedur',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'SDM',
    bidangCode: 'BID-04',
    subbidang: 'Administrasi GTK',
    sasaran: 'Data dan administrasi GTK akurat, lengkap, mutakhir, dan mudah ditelusuri.',
    indikator: 'Persentase data GTK lengkap',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'SDM',
    bidangCode: 'BID-04',
    subbidang: 'Administrasi GTK',
    sasaran: 'Data dan administrasi GTK akurat, lengkap, mutakhir, dan mudah ditelusuri.',
    indikator: 'Persentase dokumen GTK valid dan belum kedaluwarsa',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '>= 98%',
    baseline: 0,
    targetVal: 98,
    satuan: '%'
  },
  {
    bidang: 'SDM',
    bidangCode: 'BID-04',
    subbidang: 'Administrasi GTK',
    sasaran: 'Data dan administrasi GTK akurat, lengkap, mutakhir, dan mudah ditelusuri.',
    indikator: 'Persentase perubahan data GTK diperbarui tepat waktu',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'SDM',
    bidangCode: 'BID-04',
    subbidang: 'Pengelolaan GTK',
    sasaran: 'Penugasan, presensi, struktur kerja, dan layanan kedinasan GTK terkelola tertib dan adil.',
    indikator: 'Persentase GTK memiliki penugasan dan jobdesk aktif',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'SDM',
    bidangCode: 'BID-04',
    subbidang: 'Pengelolaan GTK',
    sasaran: 'Penugasan, presensi, struktur kerja, dan layanan kedinasan GTK terkelola tertib dan adil.',
    indikator: 'Tingkat kehadiran GTK',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'SDM',
    bidangCode: 'BID-04',
    subbidang: 'Pengelolaan GTK',
    sasaran: 'Penugasan, presensi, struktur kerja, dan layanan kedinasan GTK terkelola tertib dan adil.',
    indikator: 'Persentase layanan kedinasan GTK selesai sesuai SLA',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'SDM',
    bidangCode: 'BID-04',
    subbidang: 'Pengelolaan GTK',
    sasaran: 'Penugasan, presensi, struktur kerja, dan layanan kedinasan GTK terkelola tertib dan adil.',
    indikator: 'Persentase posisi organisasi memiliki pengganti/backup',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'SDM',
    bidangCode: 'BID-04',
    subbidang: 'Peningkatan Kualitas GTK',
    sasaran: 'Kompetensi GTK meningkat secara berkelanjutan dan berdampak pada mutu pembelajaran/pengelolaan.',
    indikator: 'Rata-rata jam pengembangan profesional per GTK',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '>= 20 jam/semester',
    baseline: 0,
    targetVal: 20,
    satuan: 'jam/GTK'
  },
  {
    bidang: 'SDM',
    bidangCode: 'BID-04',
    subbidang: 'Peningkatan Kualitas GTK',
    sasaran: 'Kompetensi GTK meningkat secara berkelanjutan dan berdampak pada mutu pembelajaran/pengelolaan.',
    indikator: 'Persentase GTK mencapai target kompetensi tahunan',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '>= 85%',
    baseline: 0,
    targetVal: 85,
    satuan: '%'
  },
  {
    bidang: 'SDM',
    bidangCode: 'BID-04',
    subbidang: 'Peningkatan Kualitas GTK',
    sasaran: 'Kompetensi GTK meningkat secara berkelanjutan dan berdampak pada mutu pembelajaran/pengelolaan.',
    indikator: 'Persentase tindak lanjut pelatihan yang diterapkan di unit kerja',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '>= 80%',
    baseline: 0,
    targetVal: 80,
    satuan: '%'
  },

  // SARPRAS
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Manajemen Sarpras',
    sasaran: 'Sarana dan prasarana pesantren dikelola berdasarkan kebutuhan, kondisi, prioritas, dan siklus hidup aset.',
    indikator: 'Persentase aset terinventarisasi dan memiliki kondisi terkini',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Manajemen Sarpras',
    sasaran: 'Sarana dan prasarana pesantren dikelola berdasarkan kebutuhan, kondisi, prioritas, dan siklus hidup aset.',
    indikator: 'Persentase rencana pemeliharaan yang terlaksana',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Manajemen Sarpras',
    sasaran: 'Sarana dan prasarana pesantren dikelola berdasarkan kebutuhan, kondisi, prioritas, dan siklus hidup aset.',
    indikator: 'Persentase kerusakan kritis yang tertangani sesuai SLA',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Prasarana',
    sasaran: 'Infrastruktur utama pesantren aman, layak, dan mampu mendukung kebutuhan belajar serta hidup santri.',
    indikator: 'Persentase prasarana memenuhi standar kelayakan',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Prasarana',
    sasaran: 'Infrastruktur utama pesantren aman, layak, dan mampu mendukung kebutuhan belajar serta hidup santri.',
    indikator: 'Persentase prasarana kritis dengan pemeriksaan berkala terlaksana',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Prasarana',
    sasaran: 'Infrastruktur utama pesantren aman, layak, dan mampu mendukung kebutuhan belajar serta hidup santri.',
    indikator: 'Jumlah insiden keselamatan akibat kondisi prasarana',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '0',
    baseline: 0,
    targetVal: 0,
    satuan: 'insiden'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Ruang',
    sasaran: 'Ruang belajar, asrama, ibadah, pelayanan, dan kegiatan santri tersedia dalam kondisi layak dan sesuai kapasitas.',
    indikator: 'Persentase ruang layak digunakan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Ruang',
    sasaran: 'Ruang belajar, asrama, ibadah, pelayanan, dan kegiatan santri tersedia dalam kondisi layak dan sesuai kapasitas.',
    indikator: 'Rasio kapasitas ruang terhadap kebutuhan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Ruang',
    sasaran: 'Ruang belajar, asrama, ibadah, pelayanan, dan kegiatan santri tersedia dalam kondisi layak dan sesuai kapasitas.',
    indikator: 'Persentase ruang yang memenuhi standar kebersihan dan kenyamanan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Pemenuhan Sarana',
    sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.',
    indikator: 'Persentase pemenuhan kebutuhan sarana prioritas',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Pemenuhan Sarana',
    sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.',
    indikator: 'Persentase pengadaan selesai tepat waktu',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Pemenuhan Sarana',
    sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.',
    indikator: 'Persentase sarana baru berfungsi sesuai spesifikasi',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Kebersihan & Hospitality',
    sasaran: 'Lingkungan layanan pesantren bersih, rapi, nyaman, ramah, dan konsisten memenuhi standar layanan santri.',
    indikator: 'Persentase area lulus inspeksi kebersihan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Kebersihan & Hospitality',
    sasaran: 'Lingkungan layanan pesantren bersih, rapi, nyaman, ramah, dan konsisten memenuhi standar layanan santri.',
    indikator: 'Rata-rata skor kepuasan santri terhadap kebersihan dan layanan lingkungan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Outcome',
    targetRaw: '>= 4/5',
    baseline: 0,
    targetVal: 80,
    satuan: 'skor (1-5)'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Kebersihan & Hospitality',
    sasaran: 'Lingkungan layanan pesantren bersih, rapi, nyaman, ramah, dan konsisten memenuhi standar layanan santri.',
    indikator: 'Persentase keluhan kebersihan yang selesai sesuai SLA',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Buku & Seragam',
    sasaran: 'Kebutuhan buku dan seragam santri terpenuhi tepat waktu, tepat ukuran, dan dapat dipertanggungjawabkan.',
    indikator: 'Persentase santri menerima buku sesuai kebutuhan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 98%',
    baseline: 0,
    targetVal: 98,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Buku & Seragam',
    sasaran: 'Kebutuhan buku dan seragam santri terpenuhi tepat waktu, tepat ukuran, dan dapat dipertanggungjawabkan.',
    indikator: 'Persentase santri menerima seragam sesuai paket dan ukuran',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 98%',
    baseline: 0,
    targetVal: 98,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Buku & Seragam',
    sasaran: 'Kebutuhan buku dan seragam santri terpenuhi tepat waktu, tepat ukuran, dan dapat dipertanggungjawabkan.',
    indikator: 'Persentase selisih stok buku/seragam dapat dijelaskan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Bangunan',
    sasaran: 'Bangunan pesantren aman, terawat, dan memenuhi persyaratan fungsi serta keselamatan.',
    indikator: 'Persentase bangunan lulus inspeksi kondisi',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Bangunan',
    sasaran: 'Bangunan pesantren aman, terawat, dan memenuhi persyaratan fungsi serta keselamatan.',
    indikator: 'Persentase rekomendasi perbaikan kritis terselesaikan',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Bangunan',
    sasaran: 'Bangunan pesantren aman, terawat, dan memenuhi persyaratan fungsi serta keselamatan.',
    indikator: 'Jumlah insiden keselamatan terkait bangunan',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '0',
    baseline: 0,
    targetVal: 0,
    satuan: 'insiden'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Teknologi Pendidikan',
    sasaran: 'Teknologi pembelajaran dan layanan digital tersedia, berfungsi, aman, dan dimanfaatkan secara efektif.',
    indikator: 'Persentase perangkat teknologi berfungsi',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Teknologi Pendidikan',
    sasaran: 'Teknologi pembelajaran dan layanan digital tersedia, berfungsi, aman, dan dimanfaatkan secara efektif.',
    indikator: 'Availability jaringan/internet untuk layanan kritis',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Process/Service',
    targetRaw: '>= 99%',
    baseline: 0,
    targetVal: 99,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Teknologi Pendidikan',
    sasaran: 'Teknologi pembelajaran dan layanan digital tersedia, berfungsi, aman, dan dimanfaatkan secara efektif.',
    indikator: 'Persentase kelas/program yang memanfaatkan teknologi sesuai kebutuhan',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '>= 80%',
    baseline: 0,
    targetVal: 80,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Lingkungan Sekolah',
    sasaran: 'Lingkungan sekolah/pesantren aman, sehat, hijau, nyaman, dan mendukung kehidupan santri.',
    indikator: 'Persentase area memenuhi standar keamanan lingkungan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Lingkungan Sekolah',
    sasaran: 'Lingkungan sekolah/pesantren aman, sehat, hijau, nyaman, dan mendukung kehidupan santri.',
    indikator: 'Persentase titik fasilitas sanitasi berfungsi',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 98%',
    baseline: 0,
    targetVal: 98,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Lingkungan Sekolah',
    sasaran: 'Lingkungan sekolah/pesantren aman, sehat, hijau, nyaman, dan mendukung kehidupan santri.',
    indikator: 'Jumlah insiden keselamatan di area lingkungan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Process/Service',
    targetRaw: '0',
    baseline: 0,
    targetVal: 0,
    satuan: 'insiden'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Kelistrikan',
    sasaran: 'Pasokan dan instalasi listrik aman, andal, dan mencukupi kebutuhan operasional pesantren.',
    indikator: 'Availability listrik',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '>= 99%',
    baseline: 0,
    targetVal: 99,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Kelistrikan',
    sasaran: 'Pasokan dan instalasi listrik aman, andal, dan mencukupi kebutuhan operasional pesantren.',
    indikator: 'Persentase inspeksi instalasi listrik terlaksana sesuai jadwal',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'SARPRAS',
    bidangCode: 'BID-05',
    subbidang: 'Kelistrikan',
    sasaran: 'Pasokan dan instalasi listrik aman, andal, dan mencukupi kebutuhan operasional pesantren.',
    indikator: 'Jumlah gangguan listrik kritis per bulan',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '<= 2',
    baseline: 0,
    targetVal: 2,
    satuan: 'gangguan'
  },

  // TATA USAHA
  {
    bidang: 'TATA USAHA',
    bidangCode: 'BID-06',
    subbidang: 'Layanan Harian',
    sasaran: 'Layanan administrasi harian kepada santri, orang tua, dan GTK cepat, akurat, ramah, dan terdokumentasi.',
    indikator: 'Persentase permintaan layanan selesai sesuai SLA',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'TATA USAHA',
    bidangCode: 'BID-06',
    subbidang: 'Layanan Harian',
    sasaran: 'Layanan administrasi harian kepada santri, orang tua, dan GTK cepat, akurat, ramah, dan terdokumentasi.',
    indikator: 'Waktu rata-rata penyelesaian layanan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Process/Service',
    targetRaw: '<= 2 hari',
    baseline: 0,
    targetVal: 2,
    satuan: 'hari'
  },
  {
    bidang: 'TATA USAHA',
    bidangCode: 'BID-06',
    subbidang: 'Layanan Harian',
    sasaran: 'Layanan administrasi harian kepada santri, orang tua, dan GTK cepat, akurat, ramah, dan terdokumentasi.',
    indikator: 'Rata-rata skor kepuasan pengguna layanan TU',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Outcome',
    targetRaw: '>= 4/5',
    baseline: 0,
    targetVal: 80,
    satuan: 'skor (1-5)'
  },
  {
    bidang: 'TATA USAHA',
    bidangCode: 'BID-06',
    subbidang: 'Administrasi Peserta Didik',
    sasaran: 'Administrasi data dan dokumen santri akurat, lengkap, mutakhir, dan mudah ditelusuri.',
    indikator: 'Persentase data santri lengkap',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'TATA USAHA',
    bidangCode: 'BID-06',
    subbidang: 'Administrasi Peserta Didik',
    sasaran: 'Administrasi data dan dokumen santri akurat, lengkap, mutakhir, dan mudah ditelusuri.',
    indikator: 'Persentase dokumen santri valid',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '>= 98%',
    baseline: 0,
    targetVal: 98,
    satuan: '%'
  },
  {
    bidang: 'TATA USAHA',
    bidangCode: 'BID-06',
    subbidang: 'Administrasi Peserta Didik',
    sasaran: 'Administrasi data dan dokumen santri akurat, lengkap, mutakhir, dan mudah ditelusuri.',
    indikator: 'Persentase permintaan dokumen santri selesai tepat waktu',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'TATA USAHA',
    bidangCode: 'BID-06',
    subbidang: 'Sistem Informasi Manajemen (Digital & Nondigital)',
    sasaran: 'Informasi manajemen tersedia akurat, aman, mudah diakses, dan mendukung pengambilan keputusan.',
    indikator: 'Persentase laporan manajemen tersedia tepat waktu',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'TATA USAHA',
    bidangCode: 'BID-06',
    subbidang: 'Sistem Informasi Manajemen (Digital & Nondigital)',
    sasaran: 'Informasi manajemen tersedia akurat, aman, mudah diakses, dan mendukung pengambilan keputusan.',
    indikator: 'Persentase data kritis tervalidasi',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 98%',
    baseline: 0,
    targetVal: 98,
    satuan: '%'
  },
  {
    bidang: 'TATA USAHA',
    bidangCode: 'BID-06',
    subbidang: 'Sistem Informasi Manajemen (Digital & Nondigital)',
    sasaran: 'Informasi manajemen tersedia akurat, aman, mudah diakses, dan mendukung pengambilan keputusan.',
    indikator: 'Availability layanan sistem informasi',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '>= 99%',
    baseline: 0,
    targetVal: 99,
    satuan: '%'
  },
  {
    bidang: 'TATA USAHA',
    bidangCode: 'BID-06',
    subbidang: 'Dapodik',
    sasaran: 'Data Dapodik akurat, lengkap, sinkron, dan diperbarui tepat waktu.',
    indikator: 'Persentase data Dapodik tervalidasi',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 99%',
    baseline: 0,
    targetVal: 99,
    satuan: '%'
  },
  {
    bidang: 'TATA USAHA',
    bidangCode: 'BID-06',
    subbidang: 'Dapodik',
    sasaran: 'Data Dapodik akurat, lengkap, sinkron, dan diperbarui tepat waktu.',
    indikator: 'Persentase sinkronisasi berhasil sesuai jadwal',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'TATA USAHA',
    bidangCode: 'BID-06',
    subbidang: 'Dapodik',
    sasaran: 'Data Dapodik akurat, lengkap, sinkron, dan diperbarui tepat waktu.',
    indikator: 'Jumlah temuan/error data kritis',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '<= 2 kasus/100 santri',
    baseline: 0,
    targetVal: 0,
    satuan: 'temuan'
  },

  // PENGELOLAAN
  {
    bidang: 'PENGELOLAAN',
    bidangCode: 'BID-07',
    subbidang: 'Legalitas',
    sasaran: 'Legalitas dan kepatuhan lembaga terpelihara, lengkap, dan dapat ditelusuri.',
    indikator: 'Persentase dokumen legalitas wajib yang valid',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'PENGELOLAAN',
    bidangCode: 'BID-07',
    subbidang: 'Legalitas',
    sasaran: 'Legalitas dan kepatuhan lembaga terpelihara, lengkap, dan dapat ditelusuri.',
    indikator: 'Persentase dokumen legalitas yang dimonitor masa berlakunya',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'PENGELOLAAN',
    bidangCode: 'BID-07',
    subbidang: 'Legalitas',
    sasaran: 'Legalitas dan kepatuhan lembaga terpelihara, lengkap, dan dapat ditelusuri.',
    indikator: 'Jumlah temuan ketidakpatuhan kritis',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '0',
    baseline: 0,
    targetVal: 0,
    satuan: 'temuan'
  },
  {
    bidang: 'PENGELOLAAN',
    bidangCode: 'BID-07',
    subbidang: 'Usaha Pengembangan Sekolah',
    sasaran: 'Program pengembangan sekolah menghasilkan peningkatan mutu, kapasitas, atau layanan yang nyata.',
    indikator: 'Persentase program pengembangan terlaksana sesuai rencana',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Process/Service',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'PENGELOLAAN',
    bidangCode: 'BID-07',
    subbidang: 'Usaha Pengembangan Sekolah',
    sasaran: 'Program pengembangan sekolah menghasilkan peningkatan mutu, kapasitas, atau layanan yang nyata.',
    indikator: 'Persentase program pengembangan mencapai outcome yang ditetapkan',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Process/Service',
    targetRaw: '>= 80%',
    baseline: 0,
    targetVal: 80,
    satuan: '%'
  },
  {
    bidang: 'PENGELOLAAN',
    bidangCode: 'BID-07',
    subbidang: 'Usaha Pengembangan Sekolah',
    sasaran: 'Program pengembangan sekolah menghasilkan peningkatan mutu, kapasitas, atau layanan yang nyata.',
    indikator: 'Jumlah inovasi/program baru yang diimplementasikan dan dievaluasi',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '>= 3/tahun',
    baseline: 0,
    targetVal: 3,
    satuan: 'program'
  },
  {
    bidang: 'PENGELOLAAN',
    bidangCode: 'BID-07',
    subbidang: 'Rapat Kerja',
    sasaran: 'Perencanaan dan koordinasi lintas unit menghasilkan keputusan yang jelas, terjadwal, dan ditindaklanjuti.',
    indikator: 'Persentase rapat kerja terlaksana sesuai kalender',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'PENGELOLAAN',
    bidangCode: 'BID-07',
    subbidang: 'Rapat Kerja',
    sasaran: 'Perencanaan dan koordinasi lintas unit menghasilkan keputusan yang jelas, terjadwal, dan ditindaklanjuti.',
    indikator: 'Persentase rapat memiliki keputusan/notulen lengkap',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'PENGELOLAAN',
    bidangCode: 'BID-07',
    subbidang: 'Rapat Kerja',
    sasaran: 'Perencanaan dan koordinasi lintas unit menghasilkan keputusan yang jelas, terjadwal, dan ditindaklanjuti.',
    indikator: 'Persentase action item rapat selesai tepat waktu',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 85%',
    baseline: 0,
    targetVal: 85,
    satuan: '%'
  },
  {
    bidang: 'PENGELOLAAN',
    bidangCode: 'BID-07',
    subbidang: 'Kontroling & Evaluasi',
    sasaran: 'Kinerja program dipantau berkala dan hasil evaluasi digunakan untuk tindakan korektif.',
    indikator: 'Persentase unit/program yang dimonitor sesuai jadwal',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'PENGELOLAAN',
    bidangCode: 'BID-07',
    subbidang: 'Kontroling & Evaluasi',
    sasaran: 'Kinerja program dipantau berkala dan hasil evaluasi digunakan untuk tindakan korektif.',
    indikator: 'Persentase temuan evaluasi yang memiliki RTL',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'PENGELOLAAN',
    bidangCode: 'BID-07',
    subbidang: 'Kontroling & Evaluasi',
    sasaran: 'Kinerja program dipantau berkala dan hasil evaluasi digunakan untuk tindakan korektif.',
    indikator: 'Persentase RTL selesai sesuai tenggat',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 85%',
    baseline: 0,
    targetVal: 85,
    satuan: '%'
  },

  // KEUANGAN
  {
    bidang: 'KEUANGAN',
    bidangCode: 'BID-08',
    subbidang: 'Perencanaan Keuangan',
    sasaran: 'Perencanaan anggaran selaras dengan sasaran, program, prioritas layanan santri, dan kemampuan pendanaan.',
    indikator: 'Persentase program prioritas memiliki alokasi anggaran',
    bsc: 'Finansial',
    jenis: 'Process/Service',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'KEUANGAN',
    bidangCode: 'BID-08',
    subbidang: 'Perencanaan Keuangan',
    sasaran: 'Perencanaan anggaran selaras dengan sasaran, program, prioritas layanan santri, dan kemampuan pendanaan.',
    indikator: 'Persentase anggaran terpetakan ke sasaran strategis',
    bsc: 'Finansial',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'KEUANGAN',
    bidangCode: 'BID-08',
    subbidang: 'Perencanaan Keuangan',
    sasaran: 'Perencanaan anggaran selaras dengan sasaran, program, prioritas layanan santri, dan kemampuan pendanaan.',
    indikator: 'Deviasi antara proyeksi dan realisasi pendapatan',
    bsc: 'Finansial',
    jenis: 'Process/Service',
    targetRaw: '<= 10%',
    baseline: 0,
    targetVal: 10,
    satuan: '%'
  },
  {
    bidang: 'KEUANGAN',
    bidangCode: 'BID-08',
    subbidang: 'Realisasi Keuangan',
    sasaran: 'Realisasi keuangan terkendali, tepat sasaran, efisien, dan sesuai anggaran.',
    indikator: 'Realisasi anggaran terhadap rencana',
    bsc: 'Finansial',
    jenis: 'Process/Service',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'KEUANGAN',
    bidangCode: 'BID-08',
    subbidang: 'Realisasi Keuangan',
    sasaran: 'Realisasi keuangan terkendali, tepat sasaran, efisien, dan sesuai anggaran.',
    indikator: 'Deviasi realisasi belanja terhadap anggaran',
    bsc: 'Finansial',
    jenis: 'Process/Service',
    targetRaw: '<= 10%',
    baseline: 0,
    targetVal: 10,
    satuan: '%'
  },
  {
    bidang: 'KEUANGAN',
    bidangCode: 'BID-08',
    subbidang: 'Realisasi Keuangan',
    sasaran: 'Realisasi keuangan terkendali, tepat sasaran, efisien, dan sesuai anggaran.',
    indikator: 'Persentase transaksi yang lengkap dokumen pendukung',
    bsc: 'Finansial',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'KEUANGAN',
    bidangCode: 'BID-08',
    subbidang: 'Laporan',
    sasaran: 'Laporan keuangan tersedia tepat waktu, akurat, lengkap, dan dapat ditelusuri.',
    indikator: 'Persentase laporan keuangan terbit tepat waktu',
    bsc: 'Finansial',
    jenis: 'Process/Service',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'KEUANGAN',
    bidangCode: 'BID-08',
    subbidang: 'Laporan',
    sasaran: 'Laporan keuangan tersedia tepat waktu, akurat, lengkap, dan dapat ditelusuri.',
    indikator: 'Jumlah koreksi material pada laporan setelah ditutup',
    bsc: 'Finansial',
    jenis: 'Output',
    targetRaw: '0',
    baseline: 0,
    targetVal: 0,
    satuan: 'koreksi'
  },
  {
    bidang: 'KEUANGAN',
    bidangCode: 'BID-08',
    subbidang: 'Laporan',
    sasaran: 'Laporan keuangan tersedia tepat waktu, akurat, lengkap, dan dapat ditelusuri.',
    indikator: 'Persentase laporan dengan rekonsiliasi selesai',
    bsc: 'Finansial',
    jenis: 'Process/Service',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'KEUANGAN',
    bidangCode: 'BID-08',
    subbidang: 'BOS',
    sasaran: 'Pengelolaan dana BOS patuh ketentuan, terdokumentasi, dan mendukung program prioritas sekolah.',
    indikator: 'Persentase penggunaan BOS sesuai RKAS/ketentuan',
    bsc: 'Finansial',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'KEUANGAN',
    bidangCode: 'BID-08',
    subbidang: 'BOS',
    sasaran: 'Pengelolaan dana BOS patuh ketentuan, terdokumentasi, dan mendukung program prioritas sekolah.',
    indikator: 'Persentase laporan BOS disampaikan tepat waktu',
    bsc: 'Finansial',
    jenis: 'Process/Service',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'KEUANGAN',
    bidangCode: 'BID-08',
    subbidang: 'BOS',
    sasaran: 'Pengelolaan dana BOS patuh ketentuan, terdokumentasi, dan mendukung program prioritas sekolah.',
    indikator: 'Jumlah temuan pemeriksaan terkait BOS',
    bsc: 'Finansial',
    jenis: 'Output',
    targetRaw: '0',
    baseline: 0,
    targetVal: 0,
    satuan: 'temuan'
  },

  // HUMAS
  {
    bidang: 'HUMAS',
    bidangCode: 'BID-09',
    subbidang: 'Hubungan Orang Tua & Komunikasi Publik',
    sasaran: 'Hubungan dengan orang tua/wali dan publik terkelola transparan, responsif, dan membangun kepercayaan.',
    indikator: 'Persentase pesan/permintaan orang tua dijawab sesuai SLA',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'HUMAS',
    bidangCode: 'BID-09',
    subbidang: 'Hubungan Orang Tua & Komunikasi Publik',
    sasaran: 'Hubungan dengan orang tua/wali dan publik terkelola transparan, responsif, dan membangun kepercayaan.',
    indikator: 'Rata-rata skor kepuasan orang tua/wali',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Outcome',
    targetRaw: '>= 4/5',
    baseline: 0,
    targetVal: 80,
    satuan: 'skor (1-5)'
  },
  {
    bidang: 'HUMAS',
    bidangCode: 'BID-09',
    subbidang: 'Hubungan Orang Tua & Komunikasi Publik',
    sasaran: 'Hubungan dengan orang tua/wali dan publik terkelola transparan, responsif, dan membangun kepercayaan.',
    indikator: 'Persentase keluhan orang tua yang selesai dengan kepastian tindak lanjut',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'HUMAS',
    bidangCode: 'BID-09',
    subbidang: 'Kemitraan & Hubungan Kelembagaan',
    sasaran: 'Kemitraan strategis memberikan manfaat nyata bagi pendidikan, layanan santri, dan pengembangan lembaga.',
    indikator: 'Jumlah mitra aktif',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 80%',
    baseline: 0,
    targetVal: 10,
    satuan: 'mitra'
  },
  {
    bidang: 'HUMAS',
    bidangCode: 'BID-09',
    subbidang: 'Kemitraan & Hubungan Kelembagaan',
    sasaran: 'Kemitraan strategis memberikan manfaat nyata bagi pendidikan, layanan santri, dan pengembangan lembaga.',
    indikator: 'Persentase kerja sama yang menghasilkan output sesuai kesepakatan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 80%',
    baseline: 0,
    targetVal: 80,
    satuan: '%'
  },
  {
    bidang: 'HUMAS',
    bidangCode: 'BID-09',
    subbidang: 'Kemitraan & Hubungan Kelembagaan',
    sasaran: 'Kemitraan strategis memberikan manfaat nyata bagi pendidikan, layanan santri, dan pengembangan lembaga.',
    indikator: 'Nilai/manfaat kemitraan yang terealisasi',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Process/Service',
    targetRaw: '>= 80%',
    baseline: 0,
    targetVal: 80,
    satuan: '%'
  },
  {
    bidang: 'HUMAS',
    bidangCode: 'BID-09',
    subbidang: 'Publikasi & Reputasi Lembaga',
    sasaran: 'Publikasi lembaga konsisten, akurat, positif, dan memperkuat reputasi sekolah/pesantren.',
    indikator: 'Persentase kalender publikasi yang terlaksana',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'HUMAS',
    bidangCode: 'BID-09',
    subbidang: 'Publikasi & Reputasi Lembaga',
    sasaran: 'Publikasi lembaga konsisten, akurat, positif, dan memperkuat reputasi sekolah/pesantren.',
    indikator: 'Persentase publikasi melalui proses verifikasi internal',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'HUMAS',
    bidangCode: 'BID-09',
    subbidang: 'Publikasi & Reputasi Lembaga',
    sasaran: 'Publikasi lembaga konsisten, akurat, positif, dan memperkuat reputasi sekolah/pesantren.',
    indikator: 'Sentimen positif publik terhadap lembaga',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Outcome',
    targetRaw: '>= 80%',
    baseline: 0,
    targetVal: 80,
    satuan: '%'
  },

  // LAYANAN LAINNYA
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'Dapur',
    sasaran: 'Layanan makan santri aman, higienis, cukup gizi, tepat waktu, efisien, dan memuaskan.',
    indikator: 'Persentase jadwal makan santri terpenuhi tepat waktu',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 98%',
    baseline: 0,
    targetVal: 98,
    satuan: '%'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'Dapur',
    sasaran: 'Layanan makan santri aman, higienis, cukup gizi, tepat waktu, efisien, dan memuaskan.',
    indikator: 'Persentase menu terlaksana sesuai siklus/menu plan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'Dapur',
    sasaran: 'Layanan makan santri aman, higienis, cukup gizi, tepat waktu, efisien, dan memuaskan.',
    indikator: 'Persentase pemeriksaan bahan baku masuk sesuai standar',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Process/Service',
    targetRaw: '>= 98%',
    baseline: 0,
    targetVal: 98,
    satuan: '%'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'Dapur',
    sasaran: 'Layanan makan santri aman, higienis, cukup gizi, tepat waktu, efisien, dan memuaskan.',
    indikator: 'Persentase makanan lolos pemeriksaan keamanan sebelum distribusi',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'Dapur',
    sasaran: 'Layanan makan santri aman, higienis, cukup gizi, tepat waktu, efisien, dan memuaskan.',
    indikator: 'Food cost per porsi terhadap standar anggaran',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Outcome',
    targetRaw: '<= 100%',
    baseline: 0,
    targetVal: 100,
    satuan: '%'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'Dapur',
    sasaran: 'Layanan makan santri aman, higienis, cukup gizi, tepat waktu, efisien, dan memuaskan.',
    indikator: 'Persentase susut/food waste terhadap produksi',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '<= 5%',
    baseline: 0,
    targetVal: 5,
    satuan: '%'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'Dapur',
    sasaran: 'Layanan makan santri aman, higienis, cukup gizi, tepat waktu, efisien, dan memuaskan.',
    indikator: 'Rata-rata skor kepuasan santri terhadap menu',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Outcome',
    targetRaw: '>= 4/5',
    baseline: 0,
    targetVal: 80,
    satuan: 'skor (1-5)'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'Dapur',
    sasaran: 'Layanan makan santri aman, higienis, cukup gizi, tepat waktu, efisien, dan memuaskan.',
    indikator: 'Jumlah insiden keamanan pangan/keracunan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Process/Service',
    targetRaw: '0',
    baseline: 0,
    targetVal: 0,
    satuan: 'insiden'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'Dapur',
    sasaran: 'Layanan makan santri aman, higienis, cukup gizi, tepat waktu, efisien, dan memuaskan.',
    indikator: 'Kepatuhan kebersihan personel dan area dapur',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Process/Service',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'UKS',
    sasaran: 'Layanan kesehatan dasar santri responsif, terdokumentasi, preventif, dan mendukung kesehatan komunitas pesantren.',
    indikator: 'Persentase santri sakit yang mendapat penanganan awal sesuai SOP',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'UKS',
    sasaran: 'Layanan kesehatan dasar santri responsif, terdokumentasi, preventif, dan mendukung kesehatan komunitas pesantren.',
    indikator: 'Waktu respons rata-rata terhadap keluhan kesehatan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '<= 15 menit',
    baseline: 0,
    targetVal: 15,
    satuan: 'menit'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'UKS',
    sasaran: 'Layanan kesehatan dasar santri responsif, terdokumentasi, preventif, dan mendukung kesehatan komunitas pesantren.',
    indikator: 'Persentase stok obat/perbekalan kritis tersedia',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'UKS',
    sasaran: 'Layanan kesehatan dasar santri responsif, terdokumentasi, preventif, dan mendukung kesehatan komunitas pesantren.',
    indikator: 'Persentase kegiatan promotif/preventif kesehatan terlaksana',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'Labkom',
    sasaran: 'Laboratorium komputer mendukung pembelajaran dan program digital dengan perangkat yang siap digunakan.',
    indikator: 'Persentase perangkat komputer siap pakai',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'Labkom',
    sasaran: 'Laboratorium komputer mendukung pembelajaran dan program digital dengan perangkat yang siap digunakan.',
    indikator: 'Availability jaringan di Labkom saat jam praktik',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '>= 98%',
    baseline: 0,
    targetVal: 98,
    satuan: '%'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'Labkom',
    sasaran: 'Laboratorium komputer mendukung pembelajaran dan program digital dengan perangkat yang siap digunakan.',
    indikator: 'Persentase sesi praktik terlaksana tanpa gangguan teknis mayor',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'Lab IPA',
    sasaran: 'Laboratorium IPA aman, siap pakai, dan mendukung eksperimen sesuai kurikulum.',
    indikator: 'Persentase alat praktik utama tersedia dan layak',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'Lab IPA',
    sasaran: 'Laboratorium IPA aman, siap pakai, dan mendukung eksperimen sesuai kurikulum.',
    indikator: 'Persentase sesi praktikum terlaksana sesuai rencana',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'Lab IPA',
    sasaran: 'Laboratorium IPA aman, siap pakai, dan mendukung eksperimen sesuai kurikulum.',
    indikator: 'Persentase kepatuhan keselamatan laboratorium',
    bsc: 'Proses Bisnis Internal',
    jenis: 'Process/Service',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'Kantin',
    sasaran: 'Layanan kantin menyediakan pangan yang aman, bersih, sehat, terjangkau, dan sesuai aturan pesantren.',
    indikator: 'Persentase tenant/penjual memenuhi standar kebersihan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 95%',
    baseline: 0,
    targetVal: 95,
    satuan: '%'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'Kantin',
    sasaran: 'Layanan kantin menyediakan pangan yang aman, bersih, sehat, terjangkau, dan sesuai aturan pesantren.',
    indikator: 'Persentase sampel/menu yang memenuhi standar keamanan pangan',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '>= 98%',
    baseline: 0,
    targetVal: 98,
    satuan: '%'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'Kantin',
    sasaran: 'Layanan kantin menyediakan pangan yang aman, bersih, sehat, terjangkau, dan sesuai aturan pesantren.',
    indikator: 'Rata-rata skor kepuasan santri terhadap kantin',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Outcome',
    targetRaw: '>= 4/5',
    baseline: 0,
    targetVal: 80,
    satuan: 'skor (1-5)'
  },
  {
    bidang: 'LAYANAN LAINNYA',
    bidangCode: 'BID-10',
    subbidang: 'Kantin',
    sasaran: 'Layanan kantin menyediakan pangan yang aman, bersih, sehat, terjangkau, dan sesuai aturan pesantren.',
    indikator: 'Jumlah keluhan kesehatan/keamanan pangan dari kantin',
    bsc: 'Pelanggan & Stakeholder',
    jenis: 'Output',
    targetRaw: '0',
    baseline: 0,
    targetVal: 0,
    satuan: 'kasus'
  },

  // LITBANG
  {
    bidang: 'LITBANG',
    bidangCode: 'BID-11',
    subbidang: 'Riset & Inovasi',
    sasaran: 'Riset dan inovasi menghasilkan solusi baru yang relevan dengan kebutuhan sekolah/pesantren.',
    indikator: 'Jumlah riset/inovasi yang selesai',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '>= 4/tahun',
    baseline: 0,
    targetVal: 4,
    satuan: 'proyek'
  },
  {
    bidang: 'LITBANG',
    bidangCode: 'BID-11',
    subbidang: 'Riset & Inovasi',
    sasaran: 'Riset dan inovasi menghasilkan solusi baru yang relevan dengan kebutuhan sekolah/pesantren.',
    indikator: 'Persentase hasil riset yang diuji coba',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '>= 75%',
    baseline: 0,
    targetVal: 75,
    satuan: '%'
  },
  {
    bidang: 'LITBANG',
    bidangCode: 'BID-11',
    subbidang: 'Riset & Inovasi',
    sasaran: 'Riset dan inovasi menghasilkan solusi baru yang relevan dengan kebutuhan sekolah/pesantren.',
    indikator: 'Persentase hasil uji coba yang diadopsi',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '>= 50%',
    baseline: 0,
    targetVal: 50,
    satuan: '%'
  },
  {
    bidang: 'LITBANG',
    bidangCode: 'BID-11',
    subbidang: 'Pengembangan Mutu & Inovasi Program',
    sasaran: 'Program sekolah/pesantren diperbaiki secara berkelanjutan berdasarkan data hasil evaluasi dan eksperimen.',
    indikator: 'Persentase program prioritas yang dievaluasi menggunakan data outcome',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Process/Service',
    targetRaw: '>= 90%',
    baseline: 0,
    targetVal: 90,
    satuan: '%'
  },
  {
    bidang: 'LITBANG',
    bidangCode: 'BID-11',
    subbidang: 'Pengembangan Mutu & Inovasi Program',
    sasaran: 'Program sekolah/pesantren diperbaiki secara berkelanjutan berdasarkan data hasil evaluasi dan eksperimen.',
    indikator: 'Persentase rekomendasi mutu yang diimplementasikan',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '>= 80%',
    baseline: 0,
    targetVal: 80,
    satuan: '%'
  },
  {
    bidang: 'LITBANG',
    bidangCode: 'BID-11',
    subbidang: 'Pengembangan Mutu & Inovasi Program',
    sasaran: 'Program sekolah/pesantren diperbaiki secara berkelanjutan berdasarkan data hasil evaluasi dan eksperimen.',
    indikator: 'Jumlah siklus perbaikan mutu yang selesai',
    bsc: 'Pembelajaran & Pertumbuhan',
    jenis: 'Output',
    targetRaw: '>= 4',
    baseline: 0,
    targetVal: 4,
    satuan: 'siklus'
  }
];

async function seedRipsMatrix() {
  console.log('=== Memulai Seeding & Standardisasi Matriks RIPS ===');

  const bscMap = {
    'Finansial': 1,
    'Pelanggan & Stakeholder': 2,
    'Proses Bisnis Internal': 3,
    'Pembelajaran & Pertumbuhan': 4
  };

  const domainMap = {};
  const subdomainMap = {};

  // List of unique domains in order
  const domainList = [
    'MANAJEMEN STRATEGIS',
    'AKADEMIK',
    'PPDB & PEMASARAN SEKOLAH',
    'SDM',
    'SARPRAS',
    'TATA USAHA',
    'PENGELOLAAN',
    'KEUANGAN',
    'HUMAS',
    'LAYANAN LAINNYA',
    'LITBANG'
  ];

  await db.transaction(async (trx) => {
    // 1. Ensure all domains exist
    for (let i = 0; i < domainList.length; i++) {
      const name = domainList[i];
      let dom = await trx('rips_domains').where({ name }).first();
      if (!dom) {
        const [id] = await trx('rips_domains').insert({
          name,
          order_index: i + 1,
          created_at: trx.fn.now(),
          updated_at: trx.fn.now()
        });
        dom = { id, name, order_index: i + 1 };
      } else {
        await trx('rips_domains').where({ id: dom.id }).update({ order_index: i + 1, updated_at: trx.fn.now() });
      }
      domainMap[name] = dom.id;
    }

    // 2. Ensure all subdomains exist
    let subOrder = 1;
    for (const item of rawData) {
      const dId = domainMap[item.bidang];
      const key = `${dId}_${item.subbidang}`;
      if (!subdomainMap[key]) {
        let sub = await trx('rips_subdomains').where({ domain_id: dId, name: item.subbidang }).first();
        if (!sub) {
          const [id] = await trx('rips_subdomains').insert({
            domain_id: dId,
            name: item.subbidang,
            order_index: subOrder++,
            created_at: trx.fn.now(),
            updated_at: trx.fn.now()
          });
          sub = { id, name: item.subbidang, domain_id: dId };
        }
        subdomainMap[key] = sub.id;
      }
    }

    // 3. Group rawData into distinct Sasaran (Goals)
    // Map key: `${bidang}|${subbidang}|${sasaran}`
    const goalGroups = new Map();
    for (const row of rawData) {
      const key = `${row.bidang}|||${row.subbidang}|||${row.sasaran}`;
      if (!goalGroups.has(key)) {
        goalGroups.set(key, {
          bidang: row.bidang,
          subbidang: row.subbidang,
          sasaran: row.sasaran,
          bsc: row.bsc,
          indicators: []
        });
      }
      goalGroups.get(key).indicators.push(row);
    }

    console.log(`Total Sasaran Unik: ${goalGroups.size}`);
    console.log(`Total Indikator Kinerja: ${rawData.length}`);

    // Clean existing goals for document ID 1, 2, 3 to cleanly insert standardized matrix
    const docIds = [1, 2, 3];
    for (const docId of docIds) {
      const existingGoals = await trx('rips_goals').where({ rips_document_id: docId }).select('id');
      const gIds = existingGoals.map(g => g.id);
      if (gIds.length > 0) {
        await trx('rips_goal_indicators').whereIn('rips_goal_id', gIds).del();
        await trx('rips_program_goal_links').whereIn('rips_goal_id', gIds).del();
        await trx('rips_goals').whereIn('id', gIds).del();
      }

      let goalCounter = 1;
      for (const [key, group] of goalGroups.entries()) {
        const domainId = domainMap[group.bidang];
        const subdomainId = subdomainMap[`${domainId}_${group.subbidang}`];
        const bscAspectId = bscMap[group.bsc] || 3;
        const prefix = docId === 1 ? 'SAS' : `SAS-U${docId - 1}`;
        const goalCode = `${prefix}-${String(goalCounter).padStart(3, '0')}`;

        const firstInd = group.indicators[0];
        const [goalId] = await trx('rips_goals').insert({
          rips_document_id: docId,
          domain_id: domainId,
          subdomain_id: subdomainId,
          bsc_aspect_id: bscAspectId,
          code: goalCode,
          title: group.sasaran,
          indicator_name: firstInd.indikator,
          indicator_unit: firstInd.satuan,
          baseline_percent: firstInd.baseline,
          target_percent: firstInd.targetVal,
          order_index: goalCounter,
          status: 'active',
          created_at: trx.fn.now(),
          updated_at: trx.fn.now()
        });

        // Insert indicators
        let indCounter = 1;
        for (const ind of group.indicators) {
          const indCode = `${goalCode}-IND-${String(indCounter).padStart(2, '0')}`;
          await trx('rips_goal_indicators').insert({
            rips_goal_id: goalId,
            code: indCode,
            name: ind.indikator,
            unit: ind.satuan,
            baseline_percent: ind.baseline,
            target_percent: ind.targetVal,
            order_index: indCounter,
            created_at: trx.fn.now(),
            updated_at: trx.fn.now()
          });
          indCounter++;
        }

        goalCounter++;
      }
      console.log(`✓ Dokumen ID #${docId} berhasil diisi ${goalCounter - 1} sasaran.`);
    }
  });

  console.log('=== Seeding Matriks RIPS Berhasil Selesai ===');
  process.exit(0);
}

seedRipsMatrix().catch((err) => {
  console.error('Error saat seeding:', err);
  process.exit(1);
});
