const db = require('../src/config/db/manajemen');

const programRows = [
  { program: 'Tim Pengembang Sekolah (TPS)', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Tim Pengembang Sekolah (TPS)', sasaran: 'Pengembangan sekolah berjalan terkoordinasi, berbasis data, dan menghasilkan tindak lanjut yang nyata.' },
  { program: 'Workshop Pengembangan Sekolah', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Tim Pengembang Sekolah (TPS)', sasaran: 'Pengembangan sekolah berjalan terkoordinasi, berbasis data, dan menghasilkan tindak lanjut yang nyata.' },
  { program: 'Analisis Konteks', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Analisis & Riset', sasaran: 'Pengambilan keputusan sekolah menggunakan data yang relevan, aktual, dan ditindaklanjuti.' },
  { program: 'Analisis Kompetitor', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Analisis & Riset', sasaran: 'Pengambilan keputusan sekolah menggunakan data yang relevan, aktual, dan ditindaklanjuti.' },
  { program: 'EVADIR (Evaluasi Diri Sekolah)', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Analisis & Riset', sasaran: 'Pengambilan keputusan sekolah menggunakan data yang relevan, aktual, dan ditindaklanjuti.' },
  { program: 'Analisis SWOT', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Analisis & Riset', sasaran: 'Pengambilan keputusan sekolah menggunakan data yang relevan, aktual, dan ditindaklanjuti.' },
  { program: 'Survei Kepuasan', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Analisis & Riset', sasaran: 'Pengambilan keputusan sekolah menggunakan data yang relevan, aktual, dan ditindaklanjuti.' },
  { program: 'Rapor Pendidikan', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Analisis & Riset', sasaran: 'Pengambilan keputusan sekolah menggunakan data yang relevan, aktual, dan ditindaklanjuti.' },
  { program: 'Trace Study Lulusan', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Analisis & Riset', sasaran: 'Pengambilan keputusan sekolah menggunakan data yang relevan, aktual, dan ditindaklanjuti.' },
  { program: 'Blue Print Sekolah', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'RIPS (Rencana Induk Pengembangan Sekolah)', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'Visi, Misi & Tujuan', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'Indikator Mutu Program, Strategi Perencanaan dan Pelaksanaan Program', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'RKJM (Rencana Kerja Jangka Menengah)', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'RKT (Rencana Kerja Tahunan)', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'Program Kerja Sekolah', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'Program Kerja Kepala Sekolah', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'Program Kerja Bidang Kurikulum', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'Program Kerja Bidang Kesiswaan', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'Program Kerja Bidang Tata Usaha', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'Program Kerja Bidang SDM', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'Program Kerja Bidang Sarpras', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'Program Kerja Bidang Keuangan', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'Program Kerja Bidang Pemasaran', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'Program Kerja Bidang Humas', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'Program Kerja Guru Kelas', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'Program Kerja Guru Mapel', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'Program Kerja Bidang Kebersihan', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'Proker Dapur', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'Proker BOS', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'Proker Operator', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'Kalender Kerja & Schedule Time', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Rencana Strategis', sasaran: 'Perencanaan strategis sekolah tersusun selaras dari arah jangka panjang sampai program tahunan.' },
  { program: 'SKL', bidang: 'AKADEMIK', subbidang: 'SKL (Standar Kompetensi Lulusan)', sasaran: 'Kompetensi lulusan pada aspek sikap, pengetahuan, dan keterampilan mencapai target sekolah.' },
  { program: 'KKM', bidang: 'AKADEMIK', subbidang: 'SKL (Standar Kompetensi Lulusan)', sasaran: 'Kompetensi lulusan pada aspek sikap, pengetahuan, dan keterampilan mencapai target sekolah.' },
  { program: 'Kriteria Kenaikan & Kelulusan', bidang: 'AKADEMIK', subbidang: 'SKL (Standar Kompetensi Lulusan)', sasaran: 'Kompetensi lulusan pada aspek sikap, pengetahuan, dan keterampilan mencapai target sekolah.' },
  { program: 'Tim Pengembang Kurikulum (TPK)', bidang: 'AKADEMIK', subbidang: 'Standar Isi', sasaran: 'Kurikulum dan perangkat pembelajaran selaras dengan profil lulusan, kebutuhan santri, dan ketentuan yang berlaku.' },
  { program: 'Workshop Pengembangan Kurikulum', bidang: 'AKADEMIK', subbidang: 'Standar Isi', sasaran: 'Kurikulum dan perangkat pembelajaran selaras dengan profil lulusan, kebutuhan santri, dan ketentuan yang berlaku.' },
  { program: 'Dokumen I Kurikulum: KSP', bidang: 'AKADEMIK', subbidang: 'Standar Isi', sasaran: 'Kurikulum dan perangkat pembelajaran selaras dengan profil lulusan, kebutuhan santri, dan ketentuan yang berlaku.' },
  { program: 'Dokumen II Kurikulum: Silabus/ATP', bidang: 'AKADEMIK', subbidang: 'Standar Isi', sasaran: 'Kurikulum dan perangkat pembelajaran selaras dengan profil lulusan, kebutuhan santri, dan ketentuan yang berlaku.' },
  { program: 'Dokumen III Kurikulum: RPP/Modul Ajar', bidang: 'AKADEMIK', subbidang: 'Standar Isi', sasaran: 'Kurikulum dan perangkat pembelajaran selaras dengan profil lulusan, kebutuhan santri, dan ketentuan yang berlaku.' },
  { program: 'Struktur Kurikulum', bidang: 'AKADEMIK', subbidang: 'Standar Isi', sasaran: 'Kurikulum dan perangkat pembelajaran selaras dengan profil lulusan, kebutuhan santri, dan ketentuan yang berlaku.' },
  { program: 'Capaian Pembelajaran (CP)', bidang: 'AKADEMIK', subbidang: 'Standar Isi', sasaran: 'Kurikulum dan perangkat pembelajaran selaras dengan profil lulusan, kebutuhan santri, dan ketentuan yang berlaku.' },
  { program: 'Kalender Pendidikan & Agenda Kegiatan', bidang: 'AKADEMIK', subbidang: 'Standar Isi', sasaran: 'Kurikulum dan perangkat pembelajaran selaras dengan profil lulusan, kebutuhan santri, dan ketentuan yang berlaku.' },
  { program: 'Agenda Kegiatan', bidang: 'AKADEMIK', subbidang: 'Standar Isi', sasaran: 'Kurikulum dan perangkat pembelajaran selaras dengan profil lulusan, kebutuhan santri, dan ketentuan yang berlaku.' },
  { program: 'Buku Pelajaran', bidang: 'AKADEMIK', subbidang: 'Standar Isi', sasaran: 'Kurikulum dan perangkat pembelajaran selaras dengan profil lulusan, kebutuhan santri, dan ketentuan yang berlaku.' },
  { program: 'Program Akademik', bidang: 'AKADEMIK', subbidang: 'Standar Isi', sasaran: 'Kurikulum dan perangkat pembelajaran selaras dengan profil lulusan, kebutuhan santri, dan ketentuan yang berlaku.' },
  { program: 'Pedoman Akademik', bidang: 'AKADEMIK', subbidang: 'Standar Isi', sasaran: 'Kurikulum dan perangkat pembelajaran selaras dengan profil lulusan, kebutuhan santri, dan ketentuan yang berlaku.' },
  { program: 'Program Takhoshush', bidang: 'AKADEMIK', subbidang: 'Standar Isi', sasaran: 'Kurikulum dan perangkat pembelajaran selaras dengan profil lulusan, kebutuhan santri, dan ketentuan yang berlaku.' },
  { program: 'Sosialisasi Program Kurikulum', bidang: 'AKADEMIK', subbidang: 'Standar Isi', sasaran: 'Kurikulum dan perangkat pembelajaran selaras dengan profil lulusan, kebutuhan santri, dan ketentuan yang berlaku.' },
  { program: 'Pedoman Pengajaran', bidang: 'AKADEMIK', subbidang: 'Intrakulikuler', sasaran: 'Proses pembelajaran reguler terlaksana efektif, terencana, dan terpantau.' },
  { program: 'Jadwal Pelajaran', bidang: 'AKADEMIK', subbidang: 'Intrakulikuler', sasaran: 'Proses pembelajaran reguler terlaksana efektif, terencana, dan terpantau.' },
  { program: 'Analisis Waktu Efektif', bidang: 'AKADEMIK', subbidang: 'Intrakulikuler', sasaran: 'Proses pembelajaran reguler terlaksana efektif, terencana, dan terpantau.' },
  { program: 'Prota & Prosem', bidang: 'AKADEMIK', subbidang: 'Intrakulikuler', sasaran: 'Proses pembelajaran reguler terlaksana efektif, terencana, dan terpantau.' },
  { program: 'Analisis Kebutuhan Bahan dan Alat Pembelajaran', bidang: 'AKADEMIK', subbidang: 'Intrakulikuler', sasaran: 'Proses pembelajaran reguler terlaksana efektif, terencana, dan terpantau.' },
  { program: 'Buku Kerja Guru (BKG)', bidang: 'AKADEMIK', subbidang: 'Intrakulikuler', sasaran: 'Proses pembelajaran reguler terlaksana efektif, terencana, dan terpantau.' },
  { program: 'Administrasi Proses Pembelajaran', bidang: 'AKADEMIK', subbidang: 'Intrakulikuler', sasaran: 'Proses pembelajaran reguler terlaksana efektif, terencana, dan terpantau.' },
  { program: 'Kehadiran Murid', bidang: 'AKADEMIK', subbidang: 'Intrakulikuler', sasaran: 'Proses pembelajaran reguler terlaksana efektif, terencana, dan terpantau.' },
  { program: 'Pelaksanaan Pembelajaran', bidang: 'AKADEMIK', subbidang: 'Intrakulikuler', sasaran: 'Proses pembelajaran reguler terlaksana efektif, terencana, dan terpantau.' },
  { program: 'Monitoring Evaluasi Pembelajaran', bidang: 'AKADEMIK', subbidang: 'Intrakulikuler', sasaran: 'Proses pembelajaran reguler terlaksana efektif, terencana, dan terpantau.' },
  { program: 'Pengayaan Kognitif Calon Lulusan', bidang: 'AKADEMIK', subbidang: 'Intrakulikuler', sasaran: 'Proses pembelajaran reguler terlaksana efektif, terencana, dan terpantau.' },
  { program: 'Drill TKA', bidang: 'AKADEMIK', subbidang: 'Intrakulikuler', sasaran: 'Proses pembelajaran reguler terlaksana efektif, terencana, dan terpantau.' },
  { program: 'Pembelajaran Ramadhan', bidang: 'AKADEMIK', subbidang: 'Intrakulikuler', sasaran: 'Proses pembelajaran reguler terlaksana efektif, terencana, dan terpantau.' },
  { program: 'Kombel', bidang: 'AKADEMIK', subbidang: 'Intrakulikuler', sasaran: 'Proses pembelajaran reguler terlaksana efektif, terencana, dan terpantau.' },
  { program: 'Refleksi Belajar', bidang: 'AKADEMIK', subbidang: 'Kokulikuler', sasaran: 'Kegiatan kokurikuler memperkuat pembelajaran dan pengembangan kompetensi santri secara terarah.' },
  { program: 'Pembelajaran Proyek', bidang: 'AKADEMIK', subbidang: 'Kokulikuler', sasaran: 'Kegiatan kokurikuler memperkuat pembelajaran dan pengembangan kompetensi santri secara terarah.' },
  { program: 'Martikulasi Literasi', bidang: 'AKADEMIK', subbidang: 'Kokulikuler', sasaran: 'Kegiatan kokurikuler memperkuat pembelajaran dan pengembangan kompetensi santri secara terarah.' },
  { program: 'Martikulasi Numerasi', bidang: 'AKADEMIK', subbidang: 'Kokulikuler', sasaran: 'Kegiatan kokurikuler memperkuat pembelajaran dan pengembangan kompetensi santri secara terarah.' },
  { program: 'Gamifikasi', bidang: 'AKADEMIK', subbidang: 'Kokulikuler', sasaran: 'Kegiatan kokurikuler memperkuat pembelajaran dan pengembangan kompetensi santri secara terarah.' },
  { program: 'Challange Board', bidang: 'AKADEMIK', subbidang: 'Kokulikuler', sasaran: 'Kegiatan kokurikuler memperkuat pembelajaran dan pengembangan kompetensi santri secara terarah.' },
  { program: 'Seminar Ilmiah', bidang: 'AKADEMIK', subbidang: 'Kokulikuler', sasaran: 'Kegiatan kokurikuler memperkuat pembelajaran dan pengembangan kompetensi santri secara terarah.' },
  { program: "Tim Pengajar Al-Qur'an", bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: "SKL & Target Al-Qur'an", bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: "Struktur Kurikulum Al-Qur'an", bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: "CP Pembelajaran Al-Qur'an", bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: "Analisis Waktu Efektif Pembelajaran Al-Qur'an", bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: "Silabus Pembelajaran Al-Qur'an", bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: "Juknis Pembelajaran Al-Qur'an", bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: "Buku Pembelajaran Al-Qur'an", bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: "Administrasi Pembelajaran Al-Qur'an", bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: "Timeline Pembelajaran Al-Qur'an", bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: "Program Kerja Pembelajaran Al-Qur'an", bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: "Sosialisasi Program Al-Qur'an", bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: 'Pelacement Test', bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: 'Halaqah', bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: "KBM Al-Qur'an", bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: "Evaluasi KBM Al-Qur'an", bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: "Gamifikasi Pembelajaran Al-Qur'an", bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: "Konseling & Refleksi Program Al-Qur'an", bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: 'Quranic Camp', bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: 'Sanad Tuhfatul Athfal', bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: 'Sanad Al-Fatihah', bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: 'Sertifikasi Tahfizh Kemenag', bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: 'Pembiasaan Tilawah', bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: 'Takhoshush Al-Qur’an Liburan', bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: "Tasmi' Akhir Al-Qur'an", bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: "Ujian Akhir Al-Qur'an", bidang: 'AKADEMIK', subbidang: "Program Unggulan Al-Qur'an", sasaran: "Capaian al-qur'an santri berkembang sesuai target program dan dilaksanakan konsisten." },
  { program: 'Tim Pengajar Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'SKL & Target Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Struktur Kurikulum Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'CP Pembelajaran Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Analisis Waktu Efektif Pembelajaran Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Silabus Pembelajaran Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Juknis Pembelajaran Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Buku Pembelajaran Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Administrasi Pembelajaran Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Timeline Pembelajaran Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Program Kerja Pembelajaran Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Sosialisasi Program Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'KBM Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Mufradat', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Muhadatsah', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Evaluasi Program Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Gamifikasi Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Konseling Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Language Camp', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Lingkungan Bahasa (Sosial)', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Lingkungan Bahasa (Fisik)', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Kelas Karantina Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Kelas Martikulasi Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Laboratorium Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Proyek Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Trip Bahasa', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Bahasa', sasaran: 'Kemampuan bahasa santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Tim Pengajar Kewirausahaan', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Kewirausahaan', sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'SKL & Target Kewirausahaan', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Kewirausahaan', sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Struktur Kurikulum Kewirausahaan', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Kewirausahaan', sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'CP Pembelajaran Kewirausahaan', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Kewirausahaan', sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Analisis Waktu Efektif Pembelajaran Kewirausahaan', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Kewirausahaan', sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Silabus Pembelajaran Kewirausahaan', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Kewirausahaan', sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Juknis Pembelajaran Kewirausahaan', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Kewirausahaan', sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Buku Pembelajaran Kewirausahaan', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Kewirausahaan', sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Administrasi Pembelajaran Kewirausahaan', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Kewirausahaan', sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Timeline Pembelajaran Kewirausahaan', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Kewirausahaan', sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Program Kerja Pembelajaran Kewirausahaan', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Kewirausahaan', sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Sosialisasi Program Kewirausahaan', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Kewirausahaan', sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Kelas Kewirausahaan', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Kewirausahaan', sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Gamifikasi Kewirausahaan', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Kewirausahaan', sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Konseling Kewirausahaan', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Kewirausahaan', sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Proyek Kewirausahaan', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Kewirausahaan', sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Trip Kewirausahaan', bidang: 'AKADEMIK', subbidang: 'Program Unggulan Kewirausahaan', sasaran: 'Kompetensi kewirausahaan santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Tim Pengajar IT', bidang: 'AKADEMIK', subbidang: 'Program Unggulan IT', sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'SKL & Target IT', bidang: 'AKADEMIK', subbidang: 'Program Unggulan IT', sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Struktur Kurikulum IT', bidang: 'AKADEMIK', subbidang: 'Program Unggulan IT', sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'CP Pembelajaran IT', bidang: 'AKADEMIK', subbidang: 'Program Unggulan IT', sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Analisis Waktu Efektif Pembelajaran IT', bidang: 'AKADEMIK', subbidang: 'Program Unggulan IT', sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Silabus Pembelajaran IT', bidang: 'AKADEMIK', subbidang: 'Program Unggulan IT', sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Juknis Pembelajaran IT', bidang: 'AKADEMIK', subbidang: 'Program Unggulan IT', sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Buku Pembelajaran IT', bidang: 'AKADEMIK', subbidang: 'Program Unggulan IT', sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Administrasi Pembelajaran IT', bidang: 'AKADEMIK', subbidang: 'Program Unggulan IT', sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Timeline Pembelajaran IT', bidang: 'AKADEMIK', subbidang: 'Program Unggulan IT', sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Program Kerja Pembelajaran IT', bidang: 'AKADEMIK', subbidang: 'Program Unggulan IT', sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Sosialisasi Program IT', bidang: 'AKADEMIK', subbidang: 'Program Unggulan IT', sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Kelas IT', bidang: 'AKADEMIK', subbidang: 'Program Unggulan IT', sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Gamifikasi IT', bidang: 'AKADEMIK', subbidang: 'Program Unggulan IT', sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Konseling IT', bidang: 'AKADEMIK', subbidang: 'Program Unggulan IT', sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Proyek IT', bidang: 'AKADEMIK', subbidang: 'Program Unggulan IT', sasaran: 'Kompetensi teknologi dan digital santri berkembang sesuai target program dan dilaksanakan konsisten.' },
  { program: 'Bimbingan & Konseling (BK)', bidang: 'AKADEMIK', subbidang: 'Psikoedukasi', sasaran: 'Santri memperoleh dukungan psikologis, sosial, dan pencegahan masalah secara terukur.' },
  { program: 'Tes Psikologi', bidang: 'AKADEMIK', subbidang: 'Psikoedukasi', sasaran: 'Santri memperoleh dukungan psikologis, sosial, dan pencegahan masalah secara terukur.' },
  { program: 'Penyuluhan Anti Bullying', bidang: 'AKADEMIK', subbidang: 'Psikoedukasi', sasaran: 'Santri memperoleh dukungan psikologis, sosial, dan pencegahan masalah secara terukur.' },
  { program: 'Screening Indikasi Anti Bullying', bidang: 'AKADEMIK', subbidang: 'Psikoedukasi', sasaran: 'Santri memperoleh dukungan psikologis, sosial, dan pencegahan masalah secara terukur.' },
  { program: 'Kelompok Bimbingan', bidang: 'AKADEMIK', subbidang: 'Psikoedukasi', sasaran: 'Santri memperoleh dukungan psikologis, sosial, dan pencegahan masalah secara terukur.' },
  { program: 'Satgas Anti Bullying', bidang: 'AKADEMIK', subbidang: 'Psikoedukasi', sasaran: 'Santri memperoleh dukungan psikologis, sosial, dan pencegahan masalah secara terukur.' },
  { program: 'Sistem Pengaduan, Penanganan dan Pencegahan Bullying', bidang: 'AKADEMIK', subbidang: 'Psikoedukasi', sasaran: 'Santri memperoleh dukungan psikologis, sosial, dan pencegahan masalah secara terukur.' },
  { program: 'Kajian Parenting', bidang: 'AKADEMIK', subbidang: 'Psikoedukasi', sasaran: 'Santri memperoleh dukungan psikologis, sosial, dan pencegahan masalah secara terukur.' },
  { program: 'Tata Tertib Siswa', bidang: 'AKADEMIK', subbidang: 'Kesiswaan', sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.' },
  { program: 'Pembiasaan Karakter', bidang: 'AKADEMIK', subbidang: 'Kesiswaan', sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.' },
  { program: 'Spiritual Morning', bidang: 'AKADEMIK', subbidang: 'Kesiswaan', sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.' },
  { program: 'Shalat Dhuha', bidang: 'AKADEMIK', subbidang: 'Kesiswaan', sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.' },
  { program: 'Upacara Hari Senin', bidang: 'AKADEMIK', subbidang: 'Kesiswaan', sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.' },
  { program: 'Class Meeting Semester 1', bidang: 'AKADEMIK', subbidang: 'Kesiswaan', sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.' },
  { program: 'Class Meeting Semester 2', bidang: 'AKADEMIK', subbidang: 'Kesiswaan', sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.' },
  { program: 'Penyambutan Kedatangan Santri Lama', bidang: 'AKADEMIK', subbidang: 'Kesiswaan', sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.' },
  { program: 'Penyambutan Kedatangan Santri Baru', bidang: 'AKADEMIK', subbidang: 'Kesiswaan', sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.' },
  { program: "MATAN (Masa Ta'aruf Santri)", bidang: 'AKADEMIK', subbidang: 'Kesiswaan', sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.' },
  { program: 'Kegiatan Awal Tahun', bidang: 'AKADEMIK', subbidang: 'Kesiswaan', sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.' },
  { program: 'Market Day', bidang: 'AKADEMIK', subbidang: 'Kesiswaan', sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.' },
  { program: 'Perpisahan', bidang: 'AKADEMIK', subbidang: 'Kesiswaan', sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.' },
  { program: 'Kelulusan', bidang: 'AKADEMIK', subbidang: 'Kesiswaan', sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.' },
  { program: 'Pengayaan Nonkognitif Calon Lulusan', bidang: 'AKADEMIK', subbidang: 'Kesiswaan', sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.' },
  { program: 'LDKS (Latihan Dasar Kepemimpinan Siswa)', bidang: 'AKADEMIK', subbidang: 'Kesiswaan', sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.' },
  { program: 'Aktivitas Sabtu Ramadhan', bidang: 'AKADEMIK', subbidang: 'Kesiswaan', sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.' },
  { program: 'Self Developement', bidang: 'AKADEMIK', subbidang: 'Kesiswaan', sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.' },
  { program: 'Tata Tertib Asrama', bidang: 'AKADEMIK', subbidang: 'Keasramaan', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: 'Kemusyrifan', bidang: 'AKADEMIK', subbidang: 'Keasramaan', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: 'Perizinan', bidang: 'AKADEMIK', subbidang: 'Keasramaan', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: 'Pembiasaan Ibadah', bidang: 'AKADEMIK', subbidang: 'Keasramaan', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: 'Muhasabah', bidang: 'AKADEMIK', subbidang: 'Keasramaan', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: "Infaq Jum'at", bidang: 'AKADEMIK', subbidang: 'Keasramaan', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: 'Muhadharah Pekanan', bidang: 'AKADEMIK', subbidang: 'Keasramaan', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: 'Muhadharah Bulanan', bidang: 'AKADEMIK', subbidang: 'Keasramaan', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: "Da'wah Journey", bidang: 'AKADEMIK', subbidang: 'Keasramaan', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: 'Penjengukan', bidang: 'AKADEMIK', subbidang: 'Keasramaan', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: 'Perpulangan', bidang: 'AKADEMIK', subbidang: 'Keasramaan', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: 'Penelponan', bidang: 'AKADEMIK', subbidang: 'Keasramaan', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: 'Program Ramadhan', bidang: 'AKADEMIK', subbidang: 'Keasramaan', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: 'Tarhib Ramadhan', bidang: 'AKADEMIK', subbidang: 'Keasramaan', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: "I'tikaf Ramadhan", bidang: 'AKADEMIK', subbidang: 'Keasramaan', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: 'Shalat Tarawih', bidang: 'AKADEMIK', subbidang: 'Keasramaan', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: '1 Muharram', bidang: 'AKADEMIK', subbidang: 'Keasramaan', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: "Isra' Mi'raj", bidang: 'AKADEMIK', subbidang: 'Keasramaan', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: 'Maulid Nabi', bidang: 'AKADEMIK', subbidang: 'Keasramaan', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: 'Pemetaan Minat & Bakat', bidang: 'AKADEMIK', subbidang: 'Bina Prestasi', sasaran: 'Potensi dan prestasi santri teridentifikasi, dibina, dan menghasilkan capaian kompetitif.' },
  { program: 'Papan Kompetisi', bidang: 'AKADEMIK', subbidang: 'Bina Prestasi', sasaran: 'Potensi dan prestasi santri teridentifikasi, dibina, dan menghasilkan capaian kompetitif.' },
  { program: 'Latihan Olimpiade', bidang: 'AKADEMIK', subbidang: 'Bina Prestasi', sasaran: 'Potensi dan prestasi santri teridentifikasi, dibina, dan menghasilkan capaian kompetitif.' },
  { program: 'Self Learning Olimpiade', bidang: 'AKADEMIK', subbidang: 'Bina Prestasi', sasaran: 'Potensi dan prestasi santri teridentifikasi, dibina, dan menghasilkan capaian kompetitif.' },
  { program: 'Lomba: PAI Fair', bidang: 'AKADEMIK', subbidang: 'Bina Prestasi', sasaran: 'Potensi dan prestasi santri teridentifikasi, dibina, dan menghasilkan capaian kompetitif.' },
  { program: 'Pembinaan Olimpiade', bidang: 'AKADEMIK', subbidang: 'Bina Prestasi', sasaran: 'Potensi dan prestasi santri teridentifikasi, dibina, dan menghasilkan capaian kompetitif.' },
  { program: 'Uji Soal MNR', bidang: 'AKADEMIK', subbidang: 'Bina Prestasi', sasaran: 'Potensi dan prestasi santri teridentifikasi, dibina, dan menghasilkan capaian kompetitif.' },
  { program: 'Program Pendidikan Karakter', bidang: 'AKADEMIK', subbidang: 'Pendidikan Karakter & Integratif', sasaran: 'Karakter, kecakapan hidup, dan pembiasaan positif santri berkembang melalui program yang konsisten.' },
  { program: 'Lingkungan Kelas Berkarakter', bidang: 'AKADEMIK', subbidang: 'Pendidikan Karakter & Integratif', sasaran: 'Karakter, kecakapan hidup, dan pembiasaan positif santri berkembang melalui program yang konsisten.' },
  { program: 'Lingkungan Sekolah Berkarakter', bidang: 'AKADEMIK', subbidang: 'Pendidikan Karakter & Integratif', sasaran: 'Karakter, kecakapan hidup, dan pembiasaan positif santri berkembang melalui program yang konsisten.' },
  { program: 'Program Liburan Tengah Semester 1', bidang: 'AKADEMIK', subbidang: 'Pendidikan Karakter & Integratif', sasaran: 'Karakter, kecakapan hidup, dan pembiasaan positif santri berkembang melalui program yang konsisten.' },
  { program: 'Program Liburan Akhir Semester 1', bidang: 'AKADEMIK', subbidang: 'Pendidikan Karakter & Integratif', sasaran: 'Karakter, kecakapan hidup, dan pembiasaan positif santri berkembang melalui program yang konsisten.' },
  { program: 'Program Liburan Tengah Semester 2', bidang: 'AKADEMIK', subbidang: 'Pendidikan Karakter & Integratif', sasaran: 'Karakter, kecakapan hidup, dan pembiasaan positif santri berkembang melalui program yang konsisten.' },
  { program: 'Program Liburan Akhir Semester 2', bidang: 'AKADEMIK', subbidang: 'Pendidikan Karakter & Integratif', sasaran: 'Karakter, kecakapan hidup, dan pembiasaan positif santri berkembang melalui program yang konsisten.' },
  { program: 'Seminar Kesehatan', bidang: 'AKADEMIK', subbidang: 'Pendidikan Karakter & Integratif', sasaran: 'Karakter, kecakapan hidup, dan pembiasaan positif santri berkembang melalui program yang konsisten.' },
  { program: 'Seminar Anti NAFZA', bidang: 'AKADEMIK', subbidang: 'Pendidikan Karakter & Integratif', sasaran: 'Karakter, kecakapan hidup, dan pembiasaan positif santri berkembang melalui program yang konsisten.' },
  { program: 'Seminar Anti Bullying', bidang: 'AKADEMIK', subbidang: 'Pendidikan Karakter & Integratif', sasaran: 'Karakter, kecakapan hidup, dan pembiasaan positif santri berkembang melalui program yang konsisten.' },
  { program: 'Seminar Anti LGBT', bidang: 'AKADEMIK', subbidang: 'Pendidikan Karakter & Integratif', sasaran: 'Karakter, kecakapan hidup, dan pembiasaan positif santri berkembang melalui program yang konsisten.' },
  { program: 'Seminar Kemandirian', bidang: 'AKADEMIK', subbidang: 'Pendidikan Karakter & Integratif', sasaran: 'Karakter, kecakapan hidup, dan pembiasaan positif santri berkembang melalui program yang konsisten.' },
  { program: 'Seminar Kedisiplinan', bidang: 'AKADEMIK', subbidang: 'Pendidikan Karakter & Integratif', sasaran: 'Karakter, kecakapan hidup, dan pembiasaan positif santri berkembang melalui program yang konsisten.' },
  { program: 'Seminar Anti Korupsi', bidang: 'AKADEMIK', subbidang: 'Pendidikan Karakter & Integratif', sasaran: 'Karakter, kecakapan hidup, dan pembiasaan positif santri berkembang melalui program yang konsisten.' },
  { program: 'Eskpo Ekstrakulikuler', bidang: 'AKADEMIK', subbidang: 'Ekstrakulikuler', sasaran: 'Program ekstrakurikuler tersedia sesuai minat santri, berjalan aktif, dan menghasilkan perkembangan kompetensi.' },
  { program: 'Ekstrakulikuler Futsal', bidang: 'AKADEMIK', subbidang: 'Ekstrakulikuler', sasaran: 'Program ekstrakurikuler tersedia sesuai minat santri, berjalan aktif, dan menghasilkan perkembangan kompetensi.' },
  { program: 'Ekstrakulikuler Badminton', bidang: 'AKADEMIK', subbidang: 'Ekstrakulikuler', sasaran: 'Program ekstrakurikuler tersedia sesuai minat santri, berjalan aktif, dan menghasilkan perkembangan kompetensi.' },
  { program: 'Ekstrakulikuler Basket', bidang: 'AKADEMIK', subbidang: 'Ekstrakulikuler', sasaran: 'Program ekstrakurikuler tersedia sesuai minat santri, berjalan aktif, dan menghasilkan perkembangan kompetensi.' },
  { program: 'Ekstrakulikuler Panahan', bidang: 'AKADEMIK', subbidang: 'Ekstrakulikuler', sasaran: 'Program ekstrakurikuler tersedia sesuai minat santri, berjalan aktif, dan menghasilkan perkembangan kompetensi.' },
  { program: 'Ekstrakulikuler Berenang', bidang: 'AKADEMIK', subbidang: 'Ekstrakulikuler', sasaran: 'Program ekstrakurikuler tersedia sesuai minat santri, berjalan aktif, dan menghasilkan perkembangan kompetensi.' },
  { program: 'Buku Kerja Guru Kelas', bidang: 'AKADEMIK', subbidang: 'Manajemen Kelas', sasaran: 'Pengelolaan kelas mendukung pembelajaran yang tertib, nyaman, aman, dan partisipatif.' },
  { program: 'Program Kerja Kelas', bidang: 'AKADEMIK', subbidang: 'Manajemen Kelas', sasaran: 'Pengelolaan kelas mendukung pembelajaran yang tertib, nyaman, aman, dan partisipatif.' },
  { program: 'Bank Data Kelas', bidang: 'AKADEMIK', subbidang: 'Manajemen Kelas', sasaran: 'Pengelolaan kelas mendukung pembelajaran yang tertib, nyaman, aman, dan partisipatif.' },
  { program: 'Struktur Organisasi Kelas', bidang: 'AKADEMIK', subbidang: 'Manajemen Kelas', sasaran: 'Pengelolaan kelas mendukung pembelajaran yang tertib, nyaman, aman, dan partisipatif.' },
  { program: 'Tata Tertib Kelas', bidang: 'AKADEMIK', subbidang: 'Manajemen Kelas', sasaran: 'Pengelolaan kelas mendukung pembelajaran yang tertib, nyaman, aman, dan partisipatif.' },
  { program: 'Piket Kelas', bidang: 'AKADEMIK', subbidang: 'Manajemen Kelas', sasaran: 'Pengelolaan kelas mendukung pembelajaran yang tertib, nyaman, aman, dan partisipatif.' },
  { program: 'Menghias Kelas', bidang: 'AKADEMIK', subbidang: 'Manajemen Kelas', sasaran: 'Pengelolaan kelas mendukung pembelajaran yang tertib, nyaman, aman, dan partisipatif.' },
  { program: 'Pemilihan OSIS', bidang: 'AKADEMIK', subbidang: 'OSIS', sasaran: 'Organisasi santri berjalan aktif, tertib, dan menjadi wahana kepemimpinan serta tanggung jawab.' },
  { program: 'Pembentukan Struktur Organisasi OSIS', bidang: 'AKADEMIK', subbidang: 'OSIS', sasaran: 'Organisasi santri berjalan aktif, tertib, dan menjadi wahana kepemimpinan serta tanggung jawab.' },
  { program: 'Pelatihan & Pembinaan OSIS', bidang: 'AKADEMIK', subbidang: 'OSIS', sasaran: 'Organisasi santri berjalan aktif, tertib, dan menjadi wahana kepemimpinan serta tanggung jawab.' },
  { program: 'LDKS OSIS', bidang: 'AKADEMIK', subbidang: 'OSIS', sasaran: 'Organisasi santri berjalan aktif, tertib, dan menjadi wahana kepemimpinan serta tanggung jawab.' },
  { program: 'Silabus Krida', bidang: 'AKADEMIK', subbidang: 'Krida (Pramuka, PASKIBRA, PMR & Kesemaptaan)', sasaran: 'Program pembinaan kedisiplinan, kebugaran, kepemimpinan, dan keterampilan khusus santri berjalan terukur.' },
  { program: 'Buku Krida', bidang: 'AKADEMIK', subbidang: 'Krida (Pramuka, PASKIBRA, PMR & Kesemaptaan)', sasaran: 'Program pembinaan kedisiplinan, kebugaran, kepemimpinan, dan keterampilan khusus santri berjalan terukur.' },
  { program: 'BKU & SKU', bidang: 'AKADEMIK', subbidang: 'Krida (Pramuka, PASKIBRA, PMR & Kesemaptaan)', sasaran: 'Program pembinaan kedisiplinan, kebugaran, kepemimpinan, dan keterampilan khusus santri berjalan terukur.' },
  { program: 'Pedoman Penilaian', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'Rencana Penilaian', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'Asesmen Diagnostik', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'Penilaian Formatif', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'Penilaian Sumatif Tengah Semester Ganjil', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'Penilaian Sumatif Akhir Semester', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'Penilaian Sumatif Tengah Semester Genap', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'Penilaian Sumatif Akhir Tahun', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'Portofolio', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'Penilaian Nonkognitif', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'Asesmen Nasional (ANBK)', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'TKA (Tes Kemampuan Akademik)', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'Ujian Akhir Sekolah (UAS)', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'Buku Nilai', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'Laporan Nilai Tengah Semester Ganjil', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'Laporan Nilai Akhir Semester Ganjil', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'Laporan Nilai Tengah Semester Genap', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'Laporan Nilai Akhir Semester Genap', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'Ijazah', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'Analisis Daya Serap', bidang: 'AKADEMIK', subbidang: 'Standar Penilaian', sasaran: 'Penilaian berlangsung objektif, lengkap, tepat waktu, dan dimanfaatkan untuk perbaikan pembelajaran.' },
  { program: 'Riset & Analisis', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Strategi Pemasaran', sasaran: 'Strategi pemasaran berbasis data meningkatkan jangkauan, minat, dan konversi calon peserta didik.' },
  { program: 'Brand Strategy', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Strategi Pemasaran', sasaran: 'Strategi pemasaran berbasis data meningkatkan jangkauan, minat, dan konversi calon peserta didik.' },
  { program: 'Strategi Pemasaran', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Strategi Pemasaran', sasaran: 'Strategi pemasaran berbasis data meningkatkan jangkauan, minat, dan konversi calon peserta didik.' },
  { program: 'Strategi Digital Marketing', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Digital Marketing', sasaran: 'Saluran digital sekolah/pesantren aktif, konsisten, dan efektif menghasilkan jangkauan serta konversi.' },
  { program: 'Optimasi Channel Digital', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Digital Marketing', sasaran: 'Saluran digital sekolah/pesantren aktif, konsisten, dan efektif menghasilkan jangkauan serta konversi.' },
  { program: 'SMM (Social Media Marketing)', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Digital Marketing', sasaran: 'Saluran digital sekolah/pesantren aktif, konsisten, dan efektif menghasilkan jangkauan serta konversi.' },
  { program: 'WhatsApp Marketing', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Digital Marketing', sasaran: 'Saluran digital sekolah/pesantren aktif, konsisten, dan efektif menghasilkan jangkauan serta konversi.' },
  { program: 'LinkedIn Broadcast', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Digital Marketing', sasaran: 'Saluran digital sekolah/pesantren aktif, konsisten, dan efektif menghasilkan jangkauan serta konversi.' },
  { program: 'E-Mail Marketing', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Digital Marketing', sasaran: 'Saluran digital sekolah/pesantren aktif, konsisten, dan efektif menghasilkan jangkauan serta konversi.' },
  { program: 'SEO', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Digital Marketing', sasaran: 'Saluran digital sekolah/pesantren aktif, konsisten, dan efektif menghasilkan jangkauan serta konversi.' },
  { program: 'Google Ads', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Digital Marketing', sasaran: 'Saluran digital sekolah/pesantren aktif, konsisten, dan efektif menghasilkan jangkauan serta konversi.' },
  { program: 'Meta Ads', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Digital Marketing', sasaran: 'Saluran digital sekolah/pesantren aktif, konsisten, dan efektif menghasilkan jangkauan serta konversi.' },
  { program: 'Podcast', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Digital Marketing', sasaran: 'Saluran digital sekolah/pesantren aktif, konsisten, dan efektif menghasilkan jangkauan serta konversi.' },
  { program: 'Live', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Digital Marketing', sasaran: 'Saluran digital sekolah/pesantren aktif, konsisten, dan efektif menghasilkan jangkauan serta konversi.' },
  { program: 'Website', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Marketing Tools', sasaran: 'Perangkat pemasaran tersedia, konsisten, mutakhir, dan mudah digunakan oleh tim.' },
  { program: 'Social Media Account', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Marketing Tools', sasaran: 'Perangkat pemasaran tersedia, konsisten, mutakhir, dan mudah digunakan oleh tim.' },
  { program: 'Media Asset', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Marketing Tools', sasaran: 'Perangkat pemasaran tersedia, konsisten, mutakhir, dan mudah digunakan oleh tim.' },
  { program: 'Brosur', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Marketing Tools', sasaran: 'Perangkat pemasaran tersedia, konsisten, mutakhir, dan mudah digunakan oleh tim.' },
  { program: 'Poster A3', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Marketing Tools', sasaran: 'Perangkat pemasaran tersedia, konsisten, mutakhir, dan mudah digunakan oleh tim.' },
  { program: 'Slide Presentasi', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Marketing Tools', sasaran: 'Perangkat pemasaran tersedia, konsisten, mutakhir, dan mudah digunakan oleh tim.' },
  { program: 'Standing/Roll Banner', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Marketing Tools', sasaran: 'Perangkat pemasaran tersedia, konsisten, mutakhir, dan mudah digunakan oleh tim.' },
  { program: 'Spanduk', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Marketing Tools', sasaran: 'Perangkat pemasaran tersedia, konsisten, mutakhir, dan mudah digunakan oleh tim.' },
  { program: 'Video Profil', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Marketing Tools', sasaran: 'Perangkat pemasaran tersedia, konsisten, mutakhir, dan mudah digunakan oleh tim.' },
  { program: 'Sticker', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Marketing Tools', sasaran: 'Perangkat pemasaran tersedia, konsisten, mutakhir, dan mudah digunakan oleh tim.' },
  { program: 'Nametag Panitia', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Marketing Tools', sasaran: 'Perangkat pemasaran tersedia, konsisten, mutakhir, dan mudah digunakan oleh tim.' },
  { program: 'Folder Google Drive PPDB', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Marketing Tools', sasaran: 'Perangkat pemasaran tersedia, konsisten, mutakhir, dan mudah digunakan oleh tim.' },
  { program: 'Pusat Informasi Digital PPDB', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Marketing Tools', sasaran: 'Perangkat pemasaran tersedia, konsisten, mutakhir, dan mudah digunakan oleh tim.' },
  { program: 'Roadshow PPDB', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Offline Marketing', sasaran: 'Aktivitas pemasaran luring menjangkau target calon santri secara efektif dan terdokumentasi.' },
  { program: 'Sebar Media Cetak', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Offline Marketing', sasaran: 'Aktivitas pemasaran luring menjangkau target calon santri secara efektif dan terdokumentasi.' },
  { program: 'Liputan Sekolah oleh TV Nasional', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Offline Marketing', sasaran: 'Aktivitas pemasaran luring menjangkau target calon santri secara efektif dan terdokumentasi.' },
  { program: 'KOL (Key Opinion Leader) Tokoh', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Offline Marketing', sasaran: 'Aktivitas pemasaran luring menjangkau target calon santri secara efektif dan terdokumentasi.' },
  { program: 'Influencer Marketing', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Offline Marketing', sasaran: 'Aktivitas pemasaran luring menjangkau target calon santri secara efektif dan terdokumentasi.' },
  { program: 'Promo Harga (Diskon/Beasiswa/Jalur Khusus dll)', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Offline Marketing', sasaran: 'Aktivitas pemasaran luring menjangkau target calon santri secara efektif dan terdokumentasi.' },
  { program: 'Program Ayo Visit ke Sekolah: English Camp', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Offline Marketing', sasaran: 'Aktivitas pemasaran luring menjangkau target calon santri secara efektif dan terdokumentasi.' },
  { program: 'Program Ayo Visit ke Sekolah: Free Manasik', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Offline Marketing', sasaran: 'Aktivitas pemasaran luring menjangkau target calon santri secara efektif dan terdokumentasi.' },
  { program: 'Program Ayo Visit ke Sekolah: Fun Bercocok Tanam', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Offline Marketing', sasaran: 'Aktivitas pemasaran luring menjangkau target calon santri secara efektif dan terdokumentasi.' },
  { program: 'Program Ayo Visit ke Sekolah: Trial Mondok', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Offline Marketing', sasaran: 'Aktivitas pemasaran luring menjangkau target calon santri secara efektif dan terdokumentasi.' },
  { program: 'Strategi Penerimaan Pendaftaran', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Penerimaan Pendaftaran', sasaran: 'Proses penerimaan peserta didik baru berjalan cepat, transparan, akurat, dan mencapai target kuota.' },
  { program: 'Penerimaan Pendaftaran', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Penerimaan Pendaftaran', sasaran: 'Proses penerimaan peserta didik baru berjalan cepat, transparan, akurat, dan mencapai target kuota.' },
  { program: 'Resepsionis', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Penerimaan Pendaftaran', sasaran: 'Proses penerimaan peserta didik baru berjalan cepat, transparan, akurat, dan mencapai target kuota.' },
  { program: 'Monev & Laporan PPDB', bidang: 'PPDB & PEMASARAN SEKOLAH', subbidang: 'Penerimaan Pendaftaran', sasaran: 'Proses penerimaan peserta didik baru berjalan cepat, transparan, akurat, dan mencapai target kuota.' },
  { program: 'Analisis Kebutuhan GTK', bidang: 'SDM', subbidang: 'Rekrutment & Mutasi', sasaran: 'Kebutuhan GTK terpenuhi dengan orang yang sesuai kompetensi, waktu, dan struktur organisasi.' },
  { program: 'Pelaksanaan Rekrutmen', bidang: 'SDM', subbidang: 'Rekrutment & Mutasi', sasaran: 'Kebutuhan GTK terpenuhi dengan orang yang sesuai kompetensi, waktu, dan struktur organisasi.' },
  { program: 'Mutasi GTK', bidang: 'SDM', subbidang: 'Rekrutment & Mutasi', sasaran: 'Kebutuhan GTK terpenuhi dengan orang yang sesuai kompetensi, waktu, dan struktur organisasi.' },
  { program: 'Budaya Organisasi', bidang: 'SDM', subbidang: 'Pedoman GTK', sasaran: 'Tata kelola GTK memiliki aturan, standar perilaku, dan pedoman kerja yang jelas serta diterapkan.' },
  { program: 'Tata Tertib GTK', bidang: 'SDM', subbidang: 'Pedoman GTK', sasaran: 'Tata kelola GTK memiliki aturan, standar perilaku, dan pedoman kerja yang jelas serta diterapkan.' },
  { program: 'Kode Etik Guru', bidang: 'SDM', subbidang: 'Pedoman GTK', sasaran: 'Tata kelola GTK memiliki aturan, standar perilaku, dan pedoman kerja yang jelas serta diterapkan.' },
  { program: 'Sumpah Guru', bidang: 'SDM', subbidang: 'Pedoman GTK', sasaran: 'Tata kelola GTK memiliki aturan, standar perilaku, dan pedoman kerja yang jelas serta diterapkan.' },
  { program: 'Data Induk GTK', bidang: 'SDM', subbidang: 'Administrasi GTK', sasaran: 'Data dan administrasi GTK akurat, lengkap, mutakhir, dan mudah ditelusuri.' },
  { program: 'Pemberkesan GTK', bidang: 'SDM', subbidang: 'Administrasi GTK', sasaran: 'Data dan administrasi GTK akurat, lengkap, mutakhir, dan mudah ditelusuri.' },
  { program: 'Pemenuhan GTK', bidang: 'SDM', subbidang: 'Administrasi GTK', sasaran: 'Data dan administrasi GTK akurat, lengkap, mutakhir, dan mudah ditelusuri.' },
  { program: 'Struktur Organisasi & Jobdesk', bidang: 'SDM', subbidang: 'Pengelolaan GTK', sasaran: 'Penugasan, presensi, struktur kerja, dan layanan kedinasan GTK terkelola tertib dan adil.' },
  { program: 'Sistem Jenjang Karir', bidang: 'SDM', subbidang: 'Pengelolaan GTK', sasaran: 'Penugasan, presensi, struktur kerja, dan layanan kedinasan GTK terkelola tertib dan adil.' },
  { program: 'Sistem Pendukung Kedinasan GTK', bidang: 'SDM', subbidang: 'Pengelolaan GTK', sasaran: 'Penugasan, presensi, struktur kerja, dan layanan kedinasan GTK terkelola tertib dan adil.' },
  { program: 'Presensi GTK', bidang: 'SDM', subbidang: 'Pengelolaan GTK', sasaran: 'Penugasan, presensi, struktur kerja, dan layanan kedinasan GTK terkelola tertib dan adil.' },
  { program: 'Uji Kompetensi Guru (UKG)', bidang: 'SDM', subbidang: 'Peningkatan Kualitas GTK', sasaran: 'Kompetensi GTK meningkat secara berkelanjutan dan berdampak pada mutu pembelajaran/pengelolaan.' },
  { program: 'Penilaian Kinerja Kepala Sekolah (PKKS)', bidang: 'SDM', subbidang: 'Peningkatan Kualitas GTK', sasaran: 'Kompetensi GTK meningkat secara berkelanjutan dan berdampak pada mutu pembelajaran/pengelolaan.' },
  { program: 'Penilaian Kinerja Guru (PKG)', bidang: 'SDM', subbidang: 'Peningkatan Kualitas GTK', sasaran: 'Kompetensi GTK meningkat secara berkelanjutan dan berdampak pada mutu pembelajaran/pengelolaan.' },
  { program: 'Evadir', bidang: 'SDM', subbidang: 'Peningkatan Kualitas GTK', sasaran: 'Kompetensi GTK meningkat secara berkelanjutan dan berdampak pada mutu pembelajaran/pengelolaan.' },
  { program: 'Peningkatan Kompetensi Berkelanjutan (PKB)', bidang: 'SDM', subbidang: 'Peningkatan Kualitas GTK', sasaran: 'Kompetensi GTK meningkat secara berkelanjutan dan berdampak pada mutu pembelajaran/pengelolaan.' },
  { program: 'Rapor Mutu Guru', bidang: 'SDM', subbidang: 'Peningkatan Kualitas GTK', sasaran: 'Kompetensi GTK meningkat secara berkelanjutan dan berdampak pada mutu pembelajaran/pengelolaan.' },
  { program: 'Tes Psikologi Guru', bidang: 'SDM', subbidang: 'Peningkatan Kualitas GTK', sasaran: 'Kompetensi GTK meningkat secara berkelanjutan dan berdampak pada mutu pembelajaran/pengelolaan.' },
  { program: 'Pelatihan Kedinasan : Peningkatan Kompetensi KS', bidang: 'SDM', subbidang: 'Peningkatan Kualitas GTK', sasaran: 'Kompetensi GTK meningkat secara berkelanjutan dan berdampak pada mutu pembelajaran/pengelolaan.' },
  { program: 'Perencanaan Sarpras', bidang: 'SARPRAS', subbidang: 'Manajemen Sarpras', sasaran: 'Sarana dan prasarana pesantren dikelola berdasarkan kebutuhan, kondisi, prioritas, dan siklus hidup aset.' },
  { program: 'Administrasi Sarpras', bidang: 'SARPRAS', subbidang: 'Manajemen Sarpras', sasaran: 'Sarana dan prasarana pesantren dikelola berdasarkan kebutuhan, kondisi, prioritas, dan siklus hidup aset.' },
  { program: 'Perencanaan Prasarana', bidang: 'SARPRAS', subbidang: 'Prasarana', sasaran: 'Infrastruktur utama pesantren aman, layak, dan mampu mendukung kebutuhan belajar serta hidup santri.' },
  { program: 'Penataan Prasarana', bidang: 'SARPRAS', subbidang: 'Prasarana', sasaran: 'Infrastruktur utama pesantren aman, layak, dan mampu mendukung kebutuhan belajar serta hidup santri.' },
  { program: 'Supervisi Prasarana', bidang: 'SARPRAS', subbidang: 'Prasarana', sasaran: 'Infrastruktur utama pesantren aman, layak, dan mampu mendukung kebutuhan belajar serta hidup santri.' },
  { program: 'Pemeliharaan Prasarana', bidang: 'SARPRAS', subbidang: 'Prasarana', sasaran: 'Infrastruktur utama pesantren aman, layak, dan mampu mendukung kebutuhan belajar serta hidup santri.' },
  { program: 'Pemenuhan Sarana Kelas', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Ruang BK', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Ruang Belajar & Membaca', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Ruang Ibadah & Halaqoh', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Laboratorium IPA', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Cooking Class Putri', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Perpustakaan', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Digital Classroom', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Lapangan Olahraga', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Lapangan Upacara', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Ruang Kesiswaan', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Aula Muhadharah', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Aula Bersama', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Asrama', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Kamar Mandi Asrama', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Ruang Laundry', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Ruang Pemanggilan', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Tempat Makan', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Kamar Musyrif', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Ruang UKS', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Kantor Manajemen', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Kantor Guru', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Ruang Tamu', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Kantin', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Gudang Logistik Habis Pakai', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Gudang Peralatan', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Gudang Mebeularian', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Gudang Bahan Dapur', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Dapur', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Ruang Laundry Putra', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Ruang Laundry Putri', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Ruang Panel', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Pos Security', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Area Parkiran', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Area Taman Sekolah', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana Jaringan', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Pemenuhan Sarana CCTV', bidang: 'SARPRAS', subbidang: 'Pemenuhan Sarana', sasaran: 'Kebutuhan sarana prioritas santri dan pembelajaran terpenuhi dengan tepat jumlah, kualitas, dan waktu.' },
  { program: 'Layanan Kebersihan', bidang: 'SARPRAS', subbidang: 'Kebersihan & Hospitality', sasaran: 'Lingkungan layanan pesantren bersih, rapi, nyaman, ramah, dan konsisten memenuhi standar layanan santri.' },
  { program: 'Hospitality Karyawan', bidang: 'SARPRAS', subbidang: 'Kebersihan & Hospitality', sasaran: 'Lingkungan layanan pesantren bersih, rapi, nyaman, ramah, dan konsisten memenuhi standar layanan santri.' },
  { program: 'Pengadaan Buku', bidang: 'SARPRAS', subbidang: 'Buku & Seragam', sasaran: 'Kebutuhan buku dan seragam santri terpenuhi tepat waktu, tepat ukuran, dan dapat dipertanggungjawabkan.' },
  { program: 'Pengadaan Seragam', bidang: 'SARPRAS', subbidang: 'Buku & Seragam', sasaran: 'Kebutuhan buku dan seragam santri terpenuhi tepat waktu, tepat ukuran, dan dapat dipertanggungjawabkan.' },
  { program: 'Analisis Kebutuhan & Pemenuhan Ruang', bidang: 'SARPRAS', subbidang: 'Bangunan', sasaran: 'Bangunan pesantren aman, terawat, dan memenuhi persyaratan fungsi serta keselamatan.' },
  { program: 'Pemeliharaan Bangunan', bidang: 'SARPRAS', subbidang: 'Bangunan', sasaran: 'Bangunan pesantren aman, terawat, dan memenuhi persyaratan fungsi serta keselamatan.' },
  { program: 'Teknologi Pendukung Pembelajaran', bidang: 'SARPRAS', subbidang: 'Teknologi Pendidikan', sasaran: 'Teknologi pembelajaran dan layanan digital tersedia, berfungsi, aman, dan dimanfaatkan secara efektif.' },
  { program: 'Teknologi Pendukung Sistem Manajemen', bidang: 'SARPRAS', subbidang: 'Teknologi Pendidikan', sasaran: 'Teknologi pembelajaran dan layanan digital tersedia, berfungsi, aman, dan dimanfaatkan secara efektif.' },
  { program: 'Teknologi Pendukung Komunikasi', bidang: 'SARPRAS', subbidang: 'Teknologi Pendidikan', sasaran: 'Teknologi pembelajaran dan layanan digital tersedia, berfungsi, aman, dan dimanfaatkan secara efektif.' },
  { program: 'Teknologi Pendukung Proyek Kegiatan', bidang: 'SARPRAS', subbidang: 'Teknologi Pendidikan', sasaran: 'Teknologi pembelajaran dan layanan digital tersedia, berfungsi, aman, dan dimanfaatkan secara efektif.' },
  { program: 'Teknologi Pendukung File Digital', bidang: 'SARPRAS', subbidang: 'Teknologi Pendidikan', sasaran: 'Teknologi pembelajaran dan layanan digital tersedia, berfungsi, aman, dan dimanfaatkan secara efektif.' },
  { program: 'Teknologi Pendukung Kantin', bidang: 'SARPRAS', subbidang: 'Teknologi Pendidikan', sasaran: 'Teknologi pembelajaran dan layanan digital tersedia, berfungsi, aman, dan dimanfaatkan secara efektif.' },
  { program: 'Lingkungan Sekolah Edukatif, Nyaman & Aman', bidang: 'SARPRAS', subbidang: 'Lingkungan Sekolah', sasaran: 'Lingkungan sekolah/pesantren aman, sehat, hijau, nyaman, dan mendukung kehidupan santri.' },
  { program: 'Lingkungan Kelas Edukatif, Nyaman & Aman', bidang: 'SARPRAS', subbidang: 'Lingkungan Sekolah', sasaran: 'Lingkungan sekolah/pesantren aman, sehat, hijau, nyaman, dan mendukung kehidupan santri.' },
  { program: 'Analisis Kebutuhan & Pemenuhan Kelistrikan', bidang: 'SARPRAS', subbidang: 'Kelistrikan', sasaran: 'Pasokan dan instalasi listrik aman, andal, dan mencukupi kebutuhan operasional pesantren.' },
  { program: 'Pemeliharaan Kelistrikan', bidang: 'SARPRAS', subbidang: 'Kelistrikan', sasaran: 'Pasokan dan instalasi listrik aman, andal, dan mencukupi kebutuhan operasional pesantren.' },
  { program: 'Sistem manajemen file dan kearsipan', bidang: 'TATA USAHA', subbidang: 'Layanan Harian', sasaran: 'Layanan administrasi harian kepada santri, orang tua, dan GTK cepat, akurat, ramah, dan terdokumentasi.' },
  { program: 'Sistem persuratan', bidang: 'TATA USAHA', subbidang: 'Layanan Harian', sasaran: 'Layanan administrasi harian kepada santri, orang tua, dan GTK cepat, akurat, ramah, dan terdokumentasi.' },
  { program: 'Penerimaan Tamu', bidang: 'TATA USAHA', subbidang: 'Layanan Harian', sasaran: 'Layanan administrasi harian kepada santri, orang tua, dan GTK cepat, akurat, ramah, dan terdokumentasi.' },
  { program: 'Data Induk Peserta Didik', bidang: 'TATA USAHA', subbidang: 'Administrasi Peserta Didik', sasaran: 'Administrasi data dan dokumen santri akurat, lengkap, mutakhir, dan mudah ditelusuri.' },
  { program: 'Pemberkasan Peserta Didik', bidang: 'TATA USAHA', subbidang: 'Administrasi Peserta Didik', sasaran: 'Administrasi data dan dokumen santri akurat, lengkap, mutakhir, dan mudah ditelusuri.' },
  { program: 'Buku Induk Peserta Didik', bidang: 'TATA USAHA', subbidang: 'Administrasi Peserta Didik', sasaran: 'Administrasi data dan dokumen santri akurat, lengkap, mutakhir, dan mudah ditelusuri.' },
  { program: 'Pemotretan Peserta Didik', bidang: 'TATA USAHA', subbidang: 'Administrasi Peserta Didik', sasaran: 'Administrasi data dan dokumen santri akurat, lengkap, mutakhir, dan mudah ditelusuri.' },
  { program: 'Mutasi Peserta Didik', bidang: 'TATA USAHA', subbidang: 'Administrasi Peserta Didik', sasaran: 'Administrasi data dan dokumen santri akurat, lengkap, mutakhir, dan mudah ditelusuri.' },
  { program: 'Pengolahan Ijazah', bidang: 'TATA USAHA', subbidang: 'Administrasi Peserta Didik', sasaran: 'Administrasi data dan dokumen santri akurat, lengkap, mutakhir, dan mudah ditelusuri.' },
  { program: 'Pusat Informasi Digital', bidang: 'TATA USAHA', subbidang: 'Sistem Informasi Manajemen (Digital & Nondigital)', sasaran: 'Informasi manajemen tersedia akurat, aman, mudah diakses, dan mendukung pengambilan keputusan.' },
  { program: 'Papan Pusat Informasi untuk Guru', bidang: 'TATA USAHA', subbidang: 'Sistem Informasi Manajemen (Digital & Nondigital)', sasaran: 'Informasi manajemen tersedia akurat, aman, mudah diakses, dan mendukung pengambilan keputusan.' },
  { program: 'Papan Pusat Informasi untuk Manajemen', bidang: 'TATA USAHA', subbidang: 'Sistem Informasi Manajemen (Digital & Nondigital)', sasaran: 'Informasi manajemen tersedia akurat, aman, mudah diakses, dan mendukung pengambilan keputusan.' },
  { program: 'Papan Statistik Sekolah', bidang: 'TATA USAHA', subbidang: 'Sistem Informasi Manajemen (Digital & Nondigital)', sasaran: 'Informasi manajemen tersedia akurat, aman, mudah diakses, dan mendukung pengambilan keputusan.' },
  { program: 'SIM Digital', bidang: 'TATA USAHA', subbidang: 'Sistem Informasi Manajemen (Digital & Nondigital)', sasaran: 'Informasi manajemen tersedia akurat, aman, mudah diakses, dan mendukung pengambilan keputusan.' },
  { program: 'Data Periodik Dapodik', bidang: 'TATA USAHA', subbidang: 'Dapodik', sasaran: 'Data Dapodik akurat, lengkap, sinkron, dan diperbarui tepat waktu.' },
  { program: 'Laporan Dapodik', bidang: 'TATA USAHA', subbidang: 'Dapodik', sasaran: 'Data Dapodik akurat, lengkap, sinkron, dan diperbarui tepat waktu.' },
  { program: 'NUPTK', bidang: 'TATA USAHA', subbidang: 'Dapodik', sasaran: 'Data Dapodik akurat, lengkap, sinkron, dan diperbarui tepat waktu.' },
  { program: 'Akun Belajar.id', bidang: 'TATA USAHA', subbidang: 'Dapodik', sasaran: 'Data Dapodik akurat, lengkap, sinkron, dan diperbarui tepat waktu.' },
  { program: 'Legalitas Sekolah', bidang: 'PENGELOLAAN', subbidang: 'Legalitas', sasaran: 'Legalitas dan kepatuhan lembaga terpelihara, lengkap, dan dapat ditelusuri.' },
  { program: 'Izin Operasional SMA', bidang: 'PENGELOLAAN', subbidang: 'Legalitas', sasaran: 'Legalitas dan kepatuhan lembaga terpelihara, lengkap, dan dapat ditelusuri.' },
  { program: 'Legalitas Yayasan', bidang: 'PENGELOLAAN', subbidang: 'Legalitas', sasaran: 'Legalitas dan kepatuhan lembaga terpelihara, lengkap, dan dapat ditelusuri.' },
  { program: 'Legalitas Kepala Sekolah', bidang: 'PENGELOLAAN', subbidang: 'Legalitas', sasaran: 'Legalitas dan kepatuhan lembaga terpelihara, lengkap, dan dapat ditelusuri.' },
  { program: 'Akreditasi', bidang: 'PENGELOLAAN', subbidang: 'Legalitas', sasaran: 'Legalitas dan kepatuhan lembaga terpelihara, lengkap, dan dapat ditelusuri.' },
  { program: 'Tim Pengembang Sekolah (TPS)', bidang: 'PENGELOLAAN', subbidang: 'Usaha Pengembangan Sekolah', sasaran: 'Program pengembangan sekolah menghasilkan peningkatan mutu, kapasitas, atau layanan yang nyata.' },
  { program: 'PBD & Rapor Pendidikan', bidang: 'PENGELOLAAN', subbidang: 'Usaha Pengembangan Sekolah', sasaran: 'Program pengembangan sekolah menghasilkan peningkatan mutu, kapasitas, atau layanan yang nyata.' },
  { program: 'Evaluasi Diri Sekolah (EDS)', bidang: 'PENGELOLAAN', subbidang: 'Usaha Pengembangan Sekolah', sasaran: 'Program pengembangan sekolah menghasilkan peningkatan mutu, kapasitas, atau layanan yang nyata.' },
  { program: 'Pengembangan Visi, Misi, Tujuan, & Strategi', bidang: 'PENGELOLAAN', subbidang: 'Usaha Pengembangan Sekolah', sasaran: 'Program pengembangan sekolah menghasilkan peningkatan mutu, kapasitas, atau layanan yang nyata.' },
  { program: 'Pengembangan Struktur Organisasi', bidang: 'PENGELOLAAN', subbidang: 'Usaha Pengembangan Sekolah', sasaran: 'Program pengembangan sekolah menghasilkan peningkatan mutu, kapasitas, atau layanan yang nyata.' },
  { program: 'Pengembangan RKJM', bidang: 'PENGELOLAAN', subbidang: 'Usaha Pengembangan Sekolah', sasaran: 'Program pengembangan sekolah menghasilkan peningkatan mutu, kapasitas, atau layanan yang nyata.' },
  { program: 'Pengembangan RKT', bidang: 'PENGELOLAAN', subbidang: 'Usaha Pengembangan Sekolah', sasaran: 'Program pengembangan sekolah menghasilkan peningkatan mutu, kapasitas, atau layanan yang nyata.' },
  { program: 'Pengembangan RAPBS', bidang: 'PENGELOLAAN', subbidang: 'Usaha Pengembangan Sekolah', sasaran: 'Program pengembangan sekolah menghasilkan peningkatan mutu, kapasitas, atau layanan yang nyata.' },
  { program: 'Pengembangan Program Kerja', bidang: 'PENGELOLAAN', subbidang: 'Usaha Pengembangan Sekolah', sasaran: 'Program pengembangan sekolah menghasilkan peningkatan mutu, kapasitas, atau layanan yang nyata.' },
  { program: 'Rapat Kerja Awal Tahun Pelajaran', bidang: 'PENGELOLAAN', subbidang: 'Rapat Kerja', sasaran: 'Perencanaan dan koordinasi lintas unit menghasilkan keputusan yang jelas, terjadwal, dan ditindaklanjuti.' },
  { program: 'Rapat Kerja Pertengahan Tahun Pelajaran', bidang: 'PENGELOLAAN', subbidang: 'Rapat Kerja', sasaran: 'Perencanaan dan koordinasi lintas unit menghasilkan keputusan yang jelas, terjadwal, dan ditindaklanjuti.' },
  { program: 'Rapat Evaluasi Pekanan', bidang: 'PENGELOLAAN', subbidang: 'Rapat Kerja', sasaran: 'Perencanaan dan koordinasi lintas unit menghasilkan keputusan yang jelas, terjadwal, dan ditindaklanjuti.' },
  { program: 'Rapat Kerja K3S', bidang: 'PENGELOLAAN', subbidang: 'Rapat Kerja', sasaran: 'Perencanaan dan koordinasi lintas unit menghasilkan keputusan yang jelas, terjadwal, dan ditindaklanjuti.' },
  { program: 'Rapat Dinas Rutin Kepala Sekolah', bidang: 'PENGELOLAAN', subbidang: 'Rapat Kerja', sasaran: 'Perencanaan dan koordinasi lintas unit menghasilkan keputusan yang jelas, terjadwal, dan ditindaklanjuti.' },
  { program: 'Rapat Dinas Rutin Operator', bidang: 'PENGELOLAAN', subbidang: 'Rapat Kerja', sasaran: 'Perencanaan dan koordinasi lintas unit menghasilkan keputusan yang jelas, terjadwal, dan ditindaklanjuti.' },
  { program: 'Buku Induk Pedoman Sekolah', bidang: 'PENGELOLAAN', subbidang: 'Kontroling & Evaluasi', sasaran: 'Kinerja program dipantau berkala dan hasil evaluasi digunakan untuk tindakan korektif.' },
  { program: 'Buku Induk SOP Sekolah', bidang: 'PENGELOLAAN', subbidang: 'Kontroling & Evaluasi', sasaran: 'Kinerja program dipantau berkala dan hasil evaluasi digunakan untuk tindakan korektif.' },
  { program: 'Supervisi Akademik', bidang: 'PENGELOLAAN', subbidang: 'Kontroling & Evaluasi', sasaran: 'Kinerja program dipantau berkala dan hasil evaluasi digunakan untuk tindakan korektif.' },
  { program: 'Supervisi Nonakademik', bidang: 'PENGELOLAAN', subbidang: 'Kontroling & Evaluasi', sasaran: 'Kinerja program dipantau berkala dan hasil evaluasi digunakan untuk tindakan korektif.' },
  { program: 'Kalender Kerja', bidang: 'PENGELOLAAN', subbidang: 'Kontroling & Evaluasi', sasaran: 'Kinerja program dipantau berkala dan hasil evaluasi digunakan untuk tindakan korektif.' },
  { program: 'Scheduling', bidang: 'PENGELOLAAN', subbidang: 'Kontroling & Evaluasi', sasaran: 'Kinerja program dipantau berkala dan hasil evaluasi digunakan untuk tindakan korektif.' },
  { program: 'Manajemen Performa & Sistem Evaluasi', bidang: 'PENGELOLAAN', subbidang: 'Kontroling & Evaluasi', sasaran: 'Kinerja program dipantau berkala dan hasil evaluasi digunakan untuk tindakan korektif.' },
  { program: 'Refleksi', bidang: 'PENGELOLAAN', subbidang: 'Kontroling & Evaluasi', sasaran: 'Kinerja program dipantau berkala dan hasil evaluasi digunakan untuk tindakan korektif.' },
  { program: 'Supervisi Jabar Beraksi', bidang: 'PENGELOLAAN', subbidang: 'Kontroling & Evaluasi', sasaran: 'Kinerja program dipantau berkala dan hasil evaluasi digunakan untuk tindakan korektif.' },
  { program: 'Pedoman Keuangan', bidang: 'KEUANGAN', subbidang: 'Perencanaan Keuangan', sasaran: 'Perencanaan anggaran selaras dengan sasaran, program, prioritas layanan santri, dan kemampuan pendanaan.' },
  { program: 'Sistem Penggajian', bidang: 'KEUANGAN', subbidang: 'Perencanaan Keuangan', sasaran: 'Perencanaan anggaran selaras dengan sasaran, program, prioritas layanan santri, dan kemampuan pendanaan.' },
  { program: 'Strategi Keuangan', bidang: 'KEUANGAN', subbidang: 'Perencanaan Keuangan', sasaran: 'Perencanaan anggaran selaras dengan sasaran, program, prioritas layanan santri, dan kemampuan pendanaan.' },
  { program: 'RAPBS', bidang: 'KEUANGAN', subbidang: 'Perencanaan Keuangan', sasaran: 'Perencanaan anggaran selaras dengan sasaran, program, prioritas layanan santri, dan kemampuan pendanaan.' },
  { program: 'Cashflow Jangka Panjang', bidang: 'KEUANGAN', subbidang: 'Perencanaan Keuangan', sasaran: 'Perencanaan anggaran selaras dengan sasaran, program, prioritas layanan santri, dan kemampuan pendanaan.' },
  { program: 'Biaya Pendidikan', bidang: 'KEUANGAN', subbidang: 'Perencanaan Keuangan', sasaran: 'Perencanaan anggaran selaras dengan sasaran, program, prioritas layanan santri, dan kemampuan pendanaan.' },
  { program: 'Pembukuan Keuangan', bidang: 'KEUANGAN', subbidang: 'Realisasi Keuangan', sasaran: 'Realisasi keuangan terkendali, tepat sasaran, efisien, dan sesuai anggaran.' },
  { program: 'Penagihan', bidang: 'KEUANGAN', subbidang: 'Realisasi Keuangan', sasaran: 'Realisasi keuangan terkendali, tepat sasaran, efisien, dan sesuai anggaran.' },
  { program: 'Layanan Kasbon Pegawai', bidang: 'KEUANGAN', subbidang: 'Realisasi Keuangan', sasaran: 'Realisasi keuangan terkendali, tepat sasaran, efisien, dan sesuai anggaran.' },
  { program: 'Diskon Pendidikan', bidang: 'KEUANGAN', subbidang: 'Realisasi Keuangan', sasaran: 'Realisasi keuangan terkendali, tepat sasaran, efisien, dan sesuai anggaran.' },
  { program: 'Audit Internal Keuangan', bidang: 'KEUANGAN', subbidang: 'Laporan', sasaran: 'Laporan keuangan tersedia tepat waktu, akurat, lengkap, dan dapat ditelusuri.' },
  { program: 'Laporan Keuangan Bulanan', bidang: 'KEUANGAN', subbidang: 'Laporan', sasaran: 'Laporan keuangan tersedia tepat waktu, akurat, lengkap, dan dapat ditelusuri.' },
  { program: 'Laporan Keuangan Tahunan', bidang: 'KEUANGAN', subbidang: 'Laporan', sasaran: 'Laporan keuangan tersedia tepat waktu, akurat, lengkap, dan dapat ditelusuri.' },
  { program: 'RAKS', bidang: 'KEUANGAN', subbidang: 'BOS', sasaran: 'Pengelolaan dana BOS patuh ketentuan, terdokumentasi, dan mendukung program prioritas sekolah.' },
  { program: 'Pembukuan', bidang: 'KEUANGAN', subbidang: 'BOS', sasaran: 'Pengelolaan dana BOS patuh ketentuan, terdokumentasi, dan mendukung program prioritas sekolah.' },
  { program: 'Laporan', bidang: 'KEUANGAN', subbidang: 'BOS', sasaran: 'Pengelolaan dana BOS patuh ketentuan, terdokumentasi, dan mendukung program prioritas sekolah.' },
  { program: 'Monev', bidang: 'KEUANGAN', subbidang: 'BOS', sasaran: 'Pengelolaan dana BOS patuh ketentuan, terdokumentasi, dan mendukung program prioritas sekolah.' },
  { program: 'Rekonsoloiasi', bidang: 'KEUANGAN', subbidang: 'BOS', sasaran: 'Pengelolaan dana BOS patuh ketentuan, terdokumentasi, dan mendukung program prioritas sekolah.' },
  { program: 'IBC (Internet Banking Corporate)', bidang: 'KEUANGAN', subbidang: 'BOS', sasaran: 'Pengelolaan dana BOS patuh ketentuan, terdokumentasi, dan mendukung program prioritas sekolah.' },
  { program: 'Pengembangan Buku Matematika Inovatif', bidang: 'LITBANG', subbidang: 'Riset & Inovasi', sasaran: 'Riset dan inovasi menghasilkan solusi baru yang relevan dengan kebutuhan sekolah/pesantren.' },
  { program: 'Program Integrasi Mutu Layanan Santri', bidang: 'PENGELOLAAN', subbidang: 'Lintas Bidang', sasaran: 'Layanan asrama mendukung keamanan, kedisiplinan, ibadah, kebersihan, dan kesejahteraan santri.' },
  { program: 'Program Dashboard Kinerja Terpadu Pesantren', bidang: 'PENGELOLAAN', subbidang: 'Lintas Bidang', sasaran: 'Kinerja program dipantau berkala dan hasil evaluasi digunakan untuk tindakan korektif.' },
  { program: 'Program Survei Kepuasan Santri & Wali Santri Terintegrasi', bidang: 'MANAJEMEN STRATEGIS', subbidang: 'Lintas Bidang', sasaran: 'Lingkungan layanan pesantren bersih, rapi, nyaman, ramah, dan konsisten memenuhi standar layanan santri.' },
  { program: 'Program Gerakan Dapur Aman, Sehat & Efisien', bidang: 'LAYANAN LAINNYA', subbidang: 'Dapur', sasaran: 'Layanan makan santri aman, higienis, cukup gizi, tepat waktu, efisien, dan memuaskan.' },
  { program: 'Program Zero Lost Learning Time', bidang: 'AKADEMIK', subbidang: 'Intrakulikuler', sasaran: 'Kegiatan kokurikuler memperkuat pembelajaran dan pengembangan kompetensi santri secara terarah.' },
  { program: 'Program Pengembangan Kompetensi GTK Berbasis Kinerja', bidang: 'SDM', subbidang: 'Peningkatan Kualitas GTK', sasaran: 'Kompetensi GTK meningkat secara berkelanjutan dan berdampak pada mutu pembelajaran/pengelolaan.' },
  { program: 'Program Perbaikan Siklus Program: Rencana–Laksana–Evaluasi–RTL', bidang: 'PENGELOLAAN', subbidang: 'Usaha Pengembangan Sekolah', sasaran: 'Kegiatan kokurikuler memperkuat pembelajaran dan pengembangan kompetensi santri secara terarah.' },
  { program: 'Program Efisiensi Anggaran Berbasis Layanan Prioritas Santri', bidang: 'KEUANGAN', subbidang: 'Perencanaan Keuangan', sasaran: 'Perencanaan anggaran selaras dengan sasaran, program, prioritas layanan santri, dan kemampuan pendanaan.' },
  { program: 'Program Transformasi Digital Administrasi & Layanan', bidang: 'TATA USAHA', subbidang: 'Sistem Informasi Manajemen (Digital & Nondigital)', sasaran: 'Informasi manajemen tersedia akurat, aman, mudah diakses, dan mendukung pengambilan keputusan.' },
  { program: 'Program Budaya Disiplin & Pembiasaan Positif Santri', bidang: 'AKADEMIK', subbidang: 'Kesiswaan', sasaran: 'Layanan pembinaan dan kegiatan santri berjalan tertib, inklusif, dan mendukung pembentukan karakter.' },
  { program: 'Program Kesehatan Preventif Santri', bidang: 'LAYANAN LAINNYA', subbidang: 'UKS', sasaran: 'Layanan kesehatan dasar santri responsif, terdokumentasi, preventif, dan mendukung kesehatan komunitas pesantren.' },
  { program: 'Program Kemitraan Strategis Berdaya Dampak', bidang: 'HUMAS', subbidang: 'Kemitraan & Hubungan Kelembagaan', sasaran: 'Kemitraan strategis memberikan manfaat nyata bagi pendidikan, layanan santri, dan pengembangan lembaga.' },
  { program: 'Program Optimalisasi & Utilisasi Sarpras Terjadwal', bidang: 'SARPRAS', subbidang: 'Manajemen Sarpras', sasaran: 'Sarana dan prasarana pesantren dikelola berdasarkan kebutuhan, kondisi, prioritas, dan siklus hidup aset.' },
  { program: 'Program Ekosistem Publikasi & Narasi Positif Lembaga', bidang: 'HUMAS', subbidang: 'Publikasi & Reputasi Lembaga', sasaran: 'Publikasi lembaga konsisten, akurat, positif, dan memperkuat reputasi sekolah/pesantren.' }
];

async function seedPrograms() {
  console.log('=== Memulai Seeding & Standardisasi Program & Upaya RIPS ===');

  await db.transaction(async (trx) => {
    // 1. Group rows by unique program name
    const programMap = new Map();
    for (const row of programRows) {
      if (!programMap.has(row.program)) {
        programMap.set(row.program, {
          name: row.program,
          bidang: row.bidang,
          subbidang: row.subbidang,
          sasaranList: new Set()
        });
      }
      if (row.sasaran) {
        programMap.get(row.program).sasaranList.add(row.sasaran.trim());
      }
    }

    console.log(`Total Program Unik: ${programMap.size}`);

    // Flagship programs identification
    const flagshipKeywords = [
      'Al-Qur',
      'Bahasa',
      'Kewirausahaan',
      'IT',
      'Program Integrasi',
      'Program Dashboard',
      'Program Survei',
      'Program Gerakan Dapur',
      'Program Zero Lost',
      'Program Pengembangan Kompetensi',
      'Program Perbaikan Siklus',
      'Program Efisiensi Anggaran',
      'Program Transformasi Digital',
      'Program Budaya Disiplin',
      'Program Kesehatan Preventif',
      'Program Kemitraan',
      'Program Optimalisasi',
      'Program Ekosistem'
    ];

    const docIds = [1, 2, 3];
    for (const docId of docIds) {
      // Get all goals for this document to link IDs
      const goals = await trx('rips_goals').where({ rips_document_id: docId }).select('id', 'title', 'code');
      const goalLookup = new Map();
      goals.forEach((g) => {
        goalLookup.set(g.title.trim(), g.id);
      });

      // Clear existing programs and links
      const existingPrograms = await trx('rips_programs').where({ rips_document_id: docId }).select('id');
      const pIds = existingPrograms.map(p => p.id);
      if (pIds.length > 0) {
        await trx('rips_program_goal_links').whereIn('rips_program_id', pIds).del();
        await trx('rips_programs').whereIn('id', pIds).del();
      }

      let progCounter = 1;
      for (const [progName, data] of programMap.entries()) {
        const isFlagship = flagshipKeywords.some(kw => progName.includes(kw)) ? 1 : 0;
        const prefix = isFlagship ? (docId === 1 ? 'PRG-UNG' : `PRG-U${docId - 1}-UNG`) : (docId === 1 ? 'PRG' : `PRG-U${docId - 1}`);
        const progCode = `${prefix}-${String(progCounter).padStart(3, '0')}`;

        const description = `Inisiatif operasional bidang ${data.bidang} (Sub: ${data.subbidang}) untuk mendukung ketercapaian sasaran mutu RIPS.`;

        const [programId] = await trx('rips_programs').insert({
          rips_document_id: docId,
          code: progCode,
          name: progName,
          description: description,
          is_flagship: isFlagship,
          order_index: progCounter,
          status: 'active',
          created_at: trx.fn.now(),
          updated_at: trx.fn.now()
        });

        // Link with goals
        for (const sasaranTitle of data.sasaranList) {
          const goalId = goalLookup.get(sasaranTitle);
          if (goalId) {
            await trx('rips_program_goal_links').insert({
              rips_program_id: programId,
              rips_goal_id: goalId,
              created_at: trx.fn.now(),
              updated_at: trx.fn.now()
            });
          }
        }

        progCounter++;
      }
      console.log(`✓ Dokumen ID #${docId} berhasil diisi ${progCounter - 1} program strategis.`);
    }
  });

  console.log('=== Seeding Program & Upaya RIPS Berhasil Selesai! ===');
  process.exit(0);
}

seedPrograms().catch((err) => {
  console.error('Error seeding programs:', err);
  process.exit(1);
});
