import {
  ShieldCheck,
  Calculator,
  GraduationCap,
  Users2,
  Trophy,
  Building2,
  Laptop,
  BookMarked,
  BarChart3,
  Presentation,
  Utensils,
  ChefHat,
  Globe,
  BookOpen,
  UserPlus,
  Compass,
  HeartHandshake
} from 'lucide-react';

/**
 * LAUNCHER_MODULES_REGISTRY
 * 
 * Master Registry 17 Modul Ekosistem Aldepos ILMS.
 * Memuat metadata lengkap untuk kompatibilitas tampilan lama dan arsitektur baru:
 * - 12 Modul Aktif ('active')
 * - 5 Modul Masa Depan ('coming_soon')
 */
export const LAUNCHER_MODULES = [
  {
    id: 'core',
    code: 'CORE-01',
    name: 'Administrasi Sistem & RBAC',
    displayName: 'Administrasi Sistem',
    moduleName: 'Core Management',
    description: 'Kelola hak akses, peran dan pengguna sistem.',
    icon: ShieldCheck,
    iconName: 'ShieldCheck',
    iconBg: 'bg-blue-50 text-blue-600 dark:bg-blue-950/60 dark:text-blue-400',
    arrowBg: 'bg-blue-50 text-blue-600 group-hover:bg-blue-600 group-hover:text-white dark:bg-blue-900/40 dark:text-blue-300 dark:group-hover:bg-blue-600',
    category: 'Utilitas & Fondasi',
    available: true,
    status: 'active',
    path: '/core/dashboard'
  },
  {
    id: 'keuangan',
    code: 'FIN-02',
    name: 'Keuangan & Kasir Digital',
    displayName: 'Keuangan & Kasir',
    moduleName: 'Keuangan & SPP',
    description: 'Transaksi, laporan keuangan dan kasir digital.',
    icon: Calculator,
    iconName: 'Calculator',
    iconBg: 'bg-emerald-50 text-emerald-600 dark:bg-emerald-950/60 dark:text-emerald-400',
    arrowBg: 'bg-emerald-50 text-emerald-600 group-hover:bg-emerald-600 group-hover:text-white dark:bg-emerald-900/40 dark:text-emerald-300 dark:group-hover:bg-emerald-600',
    category: 'Finansial & Bisnis',
    available: true,
    status: 'active',
    path: '/keuangan/dashboard'
  },
  {
    id: 'akademik',
    code: 'AKD-03',
    name: 'Akademik & Kurikulum',
    displayName: 'Akademik & Kurikulum',
    moduleName: 'Manajemen Akademik',
    description: 'Kelola data akademik dan kurikulum sekolah.',
    icon: GraduationCap,
    iconName: 'GraduationCap',
    iconBg: 'bg-indigo-50 text-indigo-600 dark:bg-indigo-950/60 dark:text-indigo-400',
    arrowBg: 'bg-indigo-50 text-indigo-600 group-hover:bg-indigo-600 group-hover:text-white dark:bg-indigo-900/40 dark:text-indigo-300 dark:group-hover:bg-indigo-600',
    category: 'Operasional Sekolah',
    available: true,
    status: 'active',
    path: '/akademik/dashboard'
  },
  {
    id: 'kepegawaian',
    code: 'SDM-04',
    name: 'SDM & Human Resource',
    displayName: 'SDM & Kepegawaian',
    moduleName: 'Kepegawaian & HRD',
    description: 'Manajemen guru, karyawan dan kepegawaian.',
    icon: Users2,
    iconName: 'Users2',
    iconBg: 'bg-orange-50 text-orange-600 dark:bg-orange-950/60 dark:text-orange-400',
    arrowBg: 'bg-orange-50 text-orange-600 group-hover:bg-orange-600 group-hover:text-white dark:bg-orange-900/40 dark:text-orange-300 dark:group-hover:bg-orange-600',
    category: 'Operasional Sekolah',
    available: true,
    status: 'active',
    path: '/kepegawaian/dashboard'
  },
  {
    id: 'kesiswaan',
    code: 'KSS-05',
    name: 'Kesiswaan & Prestasi',
    displayName: 'Kesiswaan & Prestasi',
    moduleName: 'Kesiswaan & Disiplin',
    description: 'Data siswa, kegiatan dan prestasi.',
    icon: Trophy,
    iconName: 'Trophy',
    iconBg: 'bg-amber-50 text-amber-600 dark:bg-amber-950/60 dark:text-amber-400',
    arrowBg: 'bg-rose-50 text-rose-600 group-hover:bg-rose-600 group-hover:text-white dark:bg-rose-900/40 dark:text-rose-300 dark:group-hover:bg-rose-600',
    category: 'Operasional Sekolah',
    available: false,
    status: 'coming_soon',
    path: '/kesiswaan/dashboard'
  },
  {
    id: 'sarpras',
    code: 'SAR-06',
    name: 'Sarana & Prasarana',
    displayName: 'Sarana & Prasarana',
    moduleName: 'Sarpras & Aset',
    description: 'Inventaris, fasilitas dan aset sekolah.',
    icon: Building2,
    iconName: 'Building2',
    iconBg: 'bg-teal-50 text-teal-600 dark:bg-teal-950/60 dark:text-teal-400',
    arrowBg: 'bg-teal-50 text-teal-600 group-hover:bg-teal-600 group-hover:text-white dark:bg-teal-900/40 dark:text-teal-300 dark:group-hover:bg-teal-600',
    category: 'Operasional Sekolah',
    available: true,
    status: 'active',
    path: '/sarpras/dashboard'
  },
  {
    id: 'perpustakaan',
    code: 'LIB-07',
    name: 'Perpustakaan Digital OPAC',
    displayName: 'Perpustakaan Digital',
    moduleName: 'Perpustakaan & OPAC',
    description: 'Katalog buku dan sirkulasi perpustakaan.',
    icon: Laptop,
    iconName: 'Library',
    iconBg: 'bg-sky-50 text-sky-600 dark:bg-sky-950/60 dark:text-sky-400',
    arrowBg: 'bg-sky-50 text-sky-600 group-hover:bg-sky-600 group-hover:text-white dark:bg-sky-900/40 dark:text-sky-300 dark:group-hover:bg-sky-600',
    category: 'Akademik & Santri',
    available: true,
    status: 'active',
    path: '/perpustakaan/dashboard'
  },
  {
    id: 'cbt',
    code: 'CBT-08',
    name: 'Ujian Daring & Bank Soal',
    displayName: 'Ujian Daring & Soal',
    moduleName: 'Computer-Based Test',
    description: 'Pelaksanaan ujian dan manajemen soal.',
    icon: BookMarked,
    iconName: 'FileText',
    iconBg: 'bg-purple-50 text-purple-600 dark:bg-purple-950/60 dark:text-purple-400',
    arrowBg: 'bg-purple-50 text-purple-600 group-hover:bg-purple-600 group-hover:text-white dark:bg-purple-900/40 dark:text-purple-300 dark:group-hover:bg-purple-600',
    category: 'Akademik & Santri',
    available: false,
    status: 'coming_soon',
    path: '/cbt/dashboard'
  },
  {
    id: 'manajemen',
    code: 'MNJ-09',
    name: 'Manajemen & Mutu Sekolah',
    displayName: 'Manajemen & Mutu',
    moduleName: 'Eksekutif Dashboard',
    description: 'Monitoring, evaluasi dan penjaminan mutu.',
    icon: BarChart3,
    iconName: 'BarChart3',
    iconBg: 'bg-yellow-50 text-yellow-600 dark:bg-yellow-950/60 dark:text-yellow-400',
    arrowBg: 'bg-amber-50 text-amber-600 group-hover:bg-amber-600 group-hover:text-white dark:bg-amber-900/40 dark:text-amber-300 dark:group-hover:bg-amber-600',
    category: 'Operasional Sekolah',
    available: true,
    status: 'active',
    path: '/manajemen/dashboard'
  },
  {
    id: 'guru',
    code: 'GUR-10',
    name: 'Portal Pendidik / Guru',
    displayName: 'Portal Guru',
    moduleName: 'Portal Pengajar',
    description: 'Fitur untuk guru dan tenaga pendidik.',
    icon: Presentation,
    iconName: 'Presentation',
    iconBg: 'bg-cyan-50 text-cyan-600 dark:bg-cyan-950/60 dark:text-cyan-400',
    arrowBg: 'bg-cyan-50 text-cyan-600 group-hover:bg-cyan-600 group-hover:text-white dark:bg-cyan-900/40 dark:text-cyan-300 dark:group-hover:bg-cyan-600',
    category: 'Portal Pengguna',
    available: true,
    status: 'active',
    path: '/guru/dashboard'
  },
  {
    id: 'kantin',
    code: 'KTN-11',
    name: 'Kantin Digital & POS',
    displayName: 'Kantin Digital',
    moduleName: 'Kantin Cashless',
    description: 'Transaksi kantin dan sistem pembayaran.',
    icon: Utensils,
    iconName: 'Utensils',
    iconBg: 'bg-pink-50 text-pink-600 dark:bg-pink-950/60 dark:text-pink-400',
    arrowBg: 'bg-rose-50 text-rose-600 group-hover:bg-rose-600 group-hover:text-white dark:bg-rose-900/40 dark:text-rose-300 dark:group-hover:bg-rose-600',
    category: 'Finansial & Bisnis',
    available: true,
    status: 'active',
    path: '/kantin/dashboard'
  },
  {
    id: 'dapur',
    code: 'DAP-12',
    name: 'Dapur & Logistik Makanan',
    displayName: 'Dapur & Logistik',
    moduleName: 'Dapur Santri',
    description: 'Pengelolaan dapur dan logistik makanan.',
    icon: ChefHat,
    iconName: 'ChefHat',
    iconBg: 'bg-emerald-50 text-emerald-600 dark:bg-emerald-950/60 dark:text-emerald-400',
    arrowBg: 'bg-emerald-50 text-emerald-600 group-hover:bg-emerald-600 group-hover:text-white dark:bg-emerald-900/40 dark:text-emerald-300 dark:group-hover:bg-emerald-600',
    category: 'Operasional Sekolah',
    available: true,
    status: 'active',
    path: '/dapur/dashboard'
  },
  {
    id: 'website-utama',
    code: 'CMS-13',
    name: 'Website Utama & Portal Berita',
    displayName: 'Website Utama',
    moduleName: 'CMS Website & Berita',
    description: 'Kelola konten website sekolah.',
    icon: Globe,
    iconName: 'Globe',
    iconBg: 'bg-blue-50 text-blue-600 dark:bg-blue-950/60 dark:text-blue-400',
    arrowBg: 'bg-blue-50 text-blue-600 group-hover:bg-blue-600 group-hover:text-white dark:bg-blue-900/40 dark:text-blue-300 dark:group-hover:bg-blue-600',
    category: 'Publik & Portal',
    available: true,
    status: 'active',
    path: '/website-utama'
  },
  {
    id: 'alquran',
    code: 'QUR-14',
    name: "Tahfidz & Al-Qur'an",
    displayName: "Tahfidz & Al-Qur'an",
    moduleName: "Tahfidz Al-Qur'an",
    description: "Setoran hafalan, mutaba'ah & tilawah Al-Qur'an.",
    icon: BookOpen,
    iconName: 'BookOpen',
    iconBg: 'bg-emerald-50 text-emerald-600 dark:bg-emerald-950/60 dark:text-emerald-400',
    arrowBg: 'bg-emerald-50 text-emerald-600 group-hover:bg-emerald-600 group-hover:text-white dark:bg-emerald-900/40 dark:text-emerald-300 dark:group-hover:bg-emerald-600',
    category: 'Akademik & Santri',
    available: true,
    status: 'active',
    path: '/alquran/dashboard'
  },
  {
    id: 'ppdb',
    code: 'PSB-15',
    name: 'PPDB & Seleksi Masuk',
    displayName: 'PPDB & Seleksi',
    moduleName: 'Penerimaan Santri Baru',
    description: 'Pendaftaran santri baru & administrasi formulir.',
    icon: UserPlus,
    iconName: 'UserPlus',
    iconBg: 'bg-teal-50 text-teal-600 dark:bg-teal-950/60 dark:text-teal-400',
    arrowBg: 'bg-teal-50 text-teal-600 group-hover:bg-teal-600 group-hover:text-white dark:bg-teal-900/40 dark:text-teal-300 dark:group-hover:bg-teal-600',
    category: 'Publik & Portal',
    available: false,
    status: 'coming_soon',
    path: '/ppdb/dashboard'
  },
  {
    id: 'bk',
    code: 'BK-16',
    name: 'Bimbingan & Konseling',
    displayName: 'Bimbingan Konseling',
    moduleName: 'Konseling & Karir',
    description: 'Catatan konseling santri & pemetaan karir.',
    icon: Compass,
    iconName: 'Compass',
    iconBg: 'bg-rose-50 text-rose-600 dark:bg-rose-950/60 dark:text-rose-400',
    arrowBg: 'bg-rose-50 text-rose-600 group-hover:bg-rose-600 group-hover:text-white dark:bg-rose-900/40 dark:text-rose-300 dark:group-hover:bg-rose-600',
    category: 'Akademik & Santri',
    available: false,
    status: 'coming_soon',
    path: '/bk/dashboard'
  },
  {
    id: 'alumni',
    code: 'ALM-17',
    name: 'Tracer Study & Alumni',
    displayName: 'Tracer & Alumni',
    moduleName: 'Portal Alumni',
    description: 'Basis data alumni & rekam jejak karir.',
    icon: HeartHandshake,
    iconName: 'Users2',
    iconBg: 'bg-violet-50 text-violet-600 dark:bg-violet-950/60 dark:text-violet-400',
    arrowBg: 'bg-violet-50 text-violet-600 group-hover:bg-violet-600 group-hover:text-white dark:bg-violet-900/40 dark:text-violet-300 dark:group-hover:bg-violet-600',
    category: 'Publik & Portal',
    available: false,
    status: 'coming_soon',
    path: '/alumni/dashboard'
  }
];

export default LAUNCHER_MODULES;
